// <auto-generated/>
#pragma warning disable CS0618
using EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Signalr.Updateorderstatus;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Signalr
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\signalr
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SignalrRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The updateorderstatus property</summary>
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Signalr.Updateorderstatus.UpdateorderstatusRequestBuilder Updateorderstatus
        {
            get => new global::EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Signalr.Updateorderstatus.UpdateorderstatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Signalr.SignalrRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SignalrRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/signalr", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Signalr.SignalrRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SignalrRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/signalr", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
