/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createInventoryStockUnitViewModelIListApiResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeCheckProductsInStockRequest, serializeInventoryStockUnitViewModelIListApiResponse, type CheckProductsInStockRequest, type InventoryStockUnitViewModelIListApiResponse, type ProblemDetails } from '../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/inventory/check-stock-quantity
 */
export interface CheckStockQuantityRequestBuilder extends BaseRequestBuilder<CheckStockQuantityRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InventoryStockUnitViewModelIListApiResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     post(body: CheckProductsInStockRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<InventoryStockUnitViewModelIListApiResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CheckProductsInStockRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CheckStockQuantityRequestBuilderUriTemplate = "{+baseurl}/api/inventory/check-stock-quantity";
/**
 * Metadata for all the requests in the request builder.
 */
export const CheckStockQuantityRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CheckStockQuantityRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createInventoryStockUnitViewModelIListApiResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCheckProductsInStockRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
