/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createQuoteViewModelApiResponseFromDiscriminatorValue, serializeOpenQuoteRequest, type OpenQuoteRequest, type ProblemDetails, type QuoteViewModelApiResponse } from '../../../models/index';
// @ts-ignore
import { type WithQuoteItemRequestBuilder, WithQuoteItemRequestBuilderNavigationMetadata, WithQuoteItemRequestBuilderRequestsMetadata } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v2/quotes
 */
export interface QuotesRequestBuilder extends BaseRequestBuilder<QuotesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.v2.quotes.item collection
     * @param quoteId Unique identifier of the item
     * @returns {WithQuoteItemRequestBuilder}
     */
     byQuoteId(quoteId: Guid) : WithQuoteItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QuoteViewModelApiResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QuoteViewModelApiResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<string>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     post(body: OpenQuoteRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<string | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: OpenQuoteRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QuotesRequestBuilderUriTemplate = "{+baseurl}/api/v2/quotes";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const QuotesRequestBuilderNavigationMetadata: Record<Exclude<keyof QuotesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byQuoteId: {
        requestsMetadata: WithQuoteItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithQuoteItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["quoteId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const QuotesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: QuotesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQuoteViewModelApiResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: QuotesRequestBuilderUriTemplate,
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "string",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeOpenQuoteRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
