// <auto-generated />
using System;
using EcommerceDDD.Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EcommerceDDD.Infrastructure.Database.Migrations
{
    [DbContext(typeof(EcommerceDDDContext))]
    partial class EcommerceDDDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EcommerceDDD.Domain.Carts.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Carts","dbo");
                });

            modelBuilder.Entity("EcommerceDDD.Domain.Core.Messaging.StoredEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StoredEvents","dbo");

                    b.HasDiscriminator();
                });

            modelBuilder.Entity("EcommerceDDD.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Customers","dbo");
                });

            modelBuilder.Entity("EcommerceDDD.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnName("StatusId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders","dbo");
                });

            modelBuilder.Entity("EcommerceDDD.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnName("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnName("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnName("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnName("StatusId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments","dbo");
                });

            modelBuilder.Entity("EcommerceDDD.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Products","dbo");
                });

            modelBuilder.Entity("EcommerceDDD.Domain.Carts.Cart", b =>
                {
                    b.HasOne("EcommerceDDD.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.OwnsMany("EcommerceDDD.Domain.Carts.CartItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CartId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("CartId");

                            b1.HasIndex("ProductId");

                            b1.ToTable("CartItems","dbo");

                            b1.WithOwner()
                                .HasForeignKey("CartId");

                            b1.HasOne("EcommerceDDD.Domain.Products.Product", "Product")
                                .WithMany()
                                .HasForeignKey("ProductId");
                        });
                });

            modelBuilder.Entity("EcommerceDDD.Domain.Orders.Order", b =>
                {
                    b.HasOne("EcommerceDDD.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.OwnsMany("EcommerceDDD.Domain.Orders.OrderLine", "OrderLines", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("OrderId", "ProductId");

                            b1.ToTable("OrderLines","dbo");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("EcommerceDDD.Domain.Shared.Money", "ProductBasePrice", b2 =>
                                {
                                    b2.Property<Guid>("OrderLineOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("OrderLineProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CurrencyCode")
                                        .HasColumnName("BaseCurrency")
                                        .HasColumnType("nvarchar(5)")
                                        .HasMaxLength(5);

                                    b2.Property<decimal>("Value")
                                        .HasColumnName("BasePrice")
                                        .HasColumnType("decimal(5,2)");

                                    b2.HasKey("OrderLineOrderId", "OrderLineProductId");

                                    b2.ToTable("OrderLines");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderLineOrderId", "OrderLineProductId");
                                });

                            b1.OwnsOne("EcommerceDDD.Domain.Shared.Money", "ProductExchangePrice", b2 =>
                                {
                                    b2.Property<Guid>("OrderLineOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("OrderLineProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CurrencyCode")
                                        .HasColumnName("ExchangeCurrency")
                                        .HasColumnType("nvarchar(5)")
                                        .HasMaxLength(5);

                                    b2.Property<decimal>("Value")
                                        .HasColumnName("ExchangePrice")
                                        .HasColumnType("decimal(5,2)");

                                    b2.HasKey("OrderLineOrderId", "OrderLineProductId");

                                    b2.ToTable("OrderLines");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderLineOrderId", "OrderLineProductId");
                                });
                        });

                    b.OwnsOne("EcommerceDDD.Domain.Shared.Money", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CurrencyCode")
                                .HasColumnName("Currency")
                                .HasColumnType("nvarchar(5)")
                                .HasMaxLength(5);

                            b1.Property<decimal>("Value")
                                .HasColumnName("TotalPrice")
                                .HasColumnType("decimal(5,2)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });
                });

            modelBuilder.Entity("EcommerceDDD.Domain.Payments.Payment", b =>
                {
                    b.HasOne("EcommerceDDD.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceDDD.Domain.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcommerceDDD.Domain.Products.Product", b =>
                {
                    b.OwnsOne("EcommerceDDD.Domain.Shared.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasColumnName("Currency")
                                .HasColumnType("nvarchar(5)")
                                .HasMaxLength(5);

                            b1.Property<decimal>("Value")
                                .HasColumnName("Price")
                                .HasColumnType("decimal(5,2)");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
