// <auto-generated/>
#pragma warning disable CS0618
using EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.Quotes;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\internal
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InternalRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The quotes property</summary>
        public global::EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.Quotes.QuotesRequestBuilder Quotes
        {
            get => new global::EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.Quotes.QuotesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.InternalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InternalRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/internal", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.InternalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InternalRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/internal", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
