/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCustomerDetailsApiResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type CustomerDetailsApiResponse, type ProblemDetails } from '../../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/customers/{customerId}/details
 */
export interface DetailsRequestBuilder extends BaseRequestBuilder<DetailsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CustomerDetailsApiResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CustomerDetailsApiResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DetailsRequestBuilderUriTemplate = "{+baseurl}/api/customers/{customerId}/details";
/**
 * Metadata for all the requests in the request builder.
 */
export const DetailsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DetailsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCustomerDetailsApiResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
