// <auto-generated/>
#pragma warning disable CS0618
using EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Accounts.Login;
using EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Accounts.Register;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Accounts
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\accounts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The login property</summary>
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Accounts.Login.LoginRequestBuilder Login
        {
            get => new global::EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Accounts.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The register property</summary>
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Accounts.Register.RegisterRequestBuilder Register
        {
            get => new global::EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Accounts.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Accounts.AccountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/accounts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.ApiGateway.Api.V2.Accounts.AccountsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/accounts", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
