/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ApiRequestBuilderNavigationMetadata, type ApiRequestBuilder } from './api/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /quoteManagement
 */
export interface QuoteManagementRequestBuilder extends BaseRequestBuilder<QuoteManagementRequestBuilder> {
    /**
     * The api property
     */
    get api(): ApiRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const QuoteManagementRequestBuilderUriTemplate = "{+baseurl}/quoteManagement";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const QuoteManagementRequestBuilderNavigationMetadata: Record<Exclude<keyof QuoteManagementRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    api: {
        navigationMetadata: ApiRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
