// <auto-generated/>
#pragma warning disable CS0618
using EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.Quotes.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.Quotes
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\internal\quotes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QuotesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the EcommerceDDD.ServiceClients.QuoteManagement.api.v2.internal.quotes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.Quotes.Item.WithQuoteItemRequestBuilder"/></returns>
        public global::EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.Quotes.Item.WithQuoteItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("quoteId", position);
                return new global::EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.Quotes.Item.WithQuoteItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the EcommerceDDD.ServiceClients.QuoteManagement.api.v2.internal.quotes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.Quotes.Item.WithQuoteItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.Quotes.Item.WithQuoteItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("quoteId", position);
                return new global::EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.Quotes.Item.WithQuoteItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.Quotes.QuotesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QuotesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/internal/quotes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.QuoteManagement.Api.V2.Internal.Quotes.QuotesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QuotesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/internal/quotes", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
