global using EcommerceDDD.Core.Infrastructure.Identity;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.Extensions.Options;
global using NSubstitute;
global using System.IdentityModel.Tokens.Jwt;
global using System.Net;
global using System.Text;
global using Xunit;
