/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ConfirmDeliveryRequestBuilderRequestsMetadata, type ConfirmDeliveryRequestBuilder } from './confirmDelivery/index.js';
// @ts-ignore
import { HistoryRequestBuilderRequestsMetadata, type HistoryRequestBuilder } from './history/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /orderProcessing/api/v2/orders/{orderId}
 */
export interface WithOrderItemRequestBuilder extends BaseRequestBuilder<WithOrderItemRequestBuilder> {
    /**
     * The confirmDelivery property
     */
    get confirmDelivery(): ConfirmDeliveryRequestBuilder;
    /**
     * The history property
     */
    get history(): HistoryRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithOrderItemRequestBuilderUriTemplate = "{+baseurl}/orderProcessing/api/v2/orders/{orderId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithOrderItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithOrderItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    confirmDelivery: {
        requestsMetadata: ConfirmDeliveryRequestBuilderRequestsMetadata,
    },
    history: {
        requestsMetadata: HistoryRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
