/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, serializePaymentRequest, type PaymentRequest, type ProblemDetails } from '../../models/index';
// @ts-ignore
import { type WithPaymentItemRequestBuilder, WithPaymentItemRequestBuilderRequestsMetadata } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/payments
 */
export interface PaymentsRequestBuilder extends BaseRequestBuilder<PaymentsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.payments.item collection
     * @param paymentId Unique identifier of the item
     * @returns {WithPaymentItemRequestBuilder}
     */
     byPaymentId(paymentId: Guid) : WithPaymentItemRequestBuilder;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<string>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     post(body: PaymentRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<string | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: PaymentRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PaymentsRequestBuilderUriTemplate = "{+baseurl}/api/payments";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PaymentsRequestBuilderNavigationMetadata: Record<Exclude<keyof PaymentsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byPaymentId: {
        requestsMetadata: WithPaymentItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["paymentId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PaymentsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PaymentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "string",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePaymentRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
