/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ApiRequestBuilderNavigationMetadata, type ApiRequestBuilder } from './api/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /productCatalog
 */
export interface ProductCatalogRequestBuilder extends BaseRequestBuilder<ProductCatalogRequestBuilder> {
    /**
     * The api property
     */
    get api(): ApiRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ProductCatalogRequestBuilderUriTemplate = "{+baseurl}/productCatalog";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProductCatalogRequestBuilderNavigationMetadata: Record<Exclude<keyof ProductCatalogRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    api: {
        navigationMetadata: ApiRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
