// <auto-generated/>
#pragma warning disable CS0618
using EcommerceDDD.ServiceClients.ApiGateway.Api.Accounts;
using EcommerceDDD.ServiceClients.ApiGateway.Api.Customers;
using EcommerceDDD.ServiceClients.ApiGateway.Api.Inventory;
using EcommerceDDD.ServiceClients.ApiGateway.Api.Orders;
using EcommerceDDD.ServiceClients.ApiGateway.Api.Payments;
using EcommerceDDD.ServiceClients.ApiGateway.Api.Products;
using EcommerceDDD.ServiceClients.ApiGateway.Api.Quotes;
using EcommerceDDD.ServiceClients.ApiGateway.Api.Shipments;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EcommerceDDD.ServiceClients.ApiGateway.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accounts property</summary>
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.Accounts.AccountsRequestBuilder Accounts
        {
            get => new global::EcommerceDDD.ServiceClients.ApiGateway.Api.Accounts.AccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customers property</summary>
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.Customers.CustomersRequestBuilder Customers
        {
            get => new global::EcommerceDDD.ServiceClients.ApiGateway.Api.Customers.CustomersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The inventory property</summary>
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.Inventory.InventoryRequestBuilder Inventory
        {
            get => new global::EcommerceDDD.ServiceClients.ApiGateway.Api.Inventory.InventoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orders property</summary>
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.Orders.OrdersRequestBuilder Orders
        {
            get => new global::EcommerceDDD.ServiceClients.ApiGateway.Api.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The payments property</summary>
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.Payments.PaymentsRequestBuilder Payments
        {
            get => new global::EcommerceDDD.ServiceClients.ApiGateway.Api.Payments.PaymentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The products property</summary>
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.Products.ProductsRequestBuilder Products
        {
            get => new global::EcommerceDDD.ServiceClients.ApiGateway.Api.Products.ProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The quotes property</summary>
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.Quotes.QuotesRequestBuilder Quotes
        {
            get => new global::EcommerceDDD.ServiceClients.ApiGateway.Api.Quotes.QuotesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shipments property</summary>
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.Shipments.ShipmentsRequestBuilder Shipments
        {
            get => new global::EcommerceDDD.ServiceClients.ApiGateway.Api.Shipments.ShipmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.ApiGateway.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.ApiGateway.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
