/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CheckStockQuantityRequestBuilderRequestsMetadata, type CheckStockQuantityRequestBuilder } from './checkStockQuantity/index';
// @ts-ignore
import { type WithProductItemRequestBuilder, WithProductItemRequestBuilderNavigationMetadata } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/inventory
 */
export interface InventoryRequestBuilder extends BaseRequestBuilder<InventoryRequestBuilder> {
    /**
     * The checkStockQuantity property
     */
    get checkStockQuantity(): CheckStockQuantityRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.inventory.item collection
     * @param productId Unique identifier of the item
     * @returns {WithProductItemRequestBuilder}
     */
     byProductId(productId: Guid) : WithProductItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const InventoryRequestBuilderUriTemplate = "{+baseurl}/api/inventory";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const InventoryRequestBuilderNavigationMetadata: Record<Exclude<keyof InventoryRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byProductId: {
        navigationMetadata: WithProductItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["productId"],
    },
    checkStockQuantity: {
        requestsMetadata: CheckStockQuantityRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
