// <auto-generated/>
#pragma warning disable CS0618
using EcommerceDDD.ServiceClients.PaymentProcessing.Api.V2.Internal.Payments.Item.Cancel;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EcommerceDDD.ServiceClients.PaymentProcessing.Api.V2.Internal.Payments.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\internal\payments\{paymentId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPaymentItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cancel property</summary>
        public global::EcommerceDDD.ServiceClients.PaymentProcessing.Api.V2.Internal.Payments.Item.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::EcommerceDDD.ServiceClients.PaymentProcessing.Api.V2.Internal.Payments.Item.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.PaymentProcessing.Api.V2.Internal.Payments.Item.WithPaymentItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPaymentItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/internal/payments/{paymentId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.PaymentProcessing.Api.V2.Internal.Payments.Item.WithPaymentItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPaymentItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/internal/payments/{paymentId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
