// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EcommerceDDD.ServiceClients.ApiGateway.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateOrderStatusRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The customerId property</summary>
        public Guid? CustomerId { get; set; }
        /// <summary>The orderId property</summary>
        public Guid? OrderId { get; set; }
        /// <summary>The orderStatusCode property</summary>
        public int? OrderStatusCode { get; set; }
        /// <summary>The orderStatusText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderStatusText { get; set; }
#nullable restore
#else
        public string OrderStatusText { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EcommerceDDD.ServiceClients.ApiGateway.Models.UpdateOrderStatusRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EcommerceDDD.ServiceClients.ApiGateway.Models.UpdateOrderStatusRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::EcommerceDDD.ServiceClients.ApiGateway.Models.UpdateOrderStatusRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customerId", n => { CustomerId = n.GetGuidValue(); } },
                { "orderId", n => { OrderId = n.GetGuidValue(); } },
                { "orderStatusCode", n => { OrderStatusCode = n.GetIntValue(); } },
                { "orderStatusText", n => { OrderStatusText = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("customerId", CustomerId);
            writer.WriteGuidValue("orderId", OrderId);
            writer.WriteIntValue("orderStatusCode", OrderStatusCode);
            writer.WriteStringValue("orderStatusText", OrderStatusText);
        }
    }
}
#pragma warning restore CS0618
