/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ApiRequestBuilderNavigationMetadata, type ApiRequestBuilder } from './api/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /orderProcessing
 */
export interface OrderProcessingRequestBuilder extends BaseRequestBuilder<OrderProcessingRequestBuilder> {
    /**
     * The api property
     */
    get api(): ApiRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const OrderProcessingRequestBuilderUriTemplate = "{+baseurl}/orderProcessing";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OrderProcessingRequestBuilderNavigationMetadata: Record<Exclude<keyof OrderProcessingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    api: {
        navigationMetadata: ApiRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
