/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AccountsRequestBuilderNavigationMetadata, type AccountsRequestBuilder } from './accounts/index';
// @ts-ignore
import { CustomersRequestBuilderNavigationMetadata, CustomersRequestBuilderRequestsMetadata, type CustomersRequestBuilder } from './customers/index';
// @ts-ignore
import { InventoryRequestBuilderNavigationMetadata, type InventoryRequestBuilder } from './inventory/index';
// @ts-ignore
import { OrdersRequestBuilderNavigationMetadata, OrdersRequestBuilderRequestsMetadata, type OrdersRequestBuilder } from './orders/index';
// @ts-ignore
import { PaymentsRequestBuilderNavigationMetadata, PaymentsRequestBuilderRequestsMetadata, type PaymentsRequestBuilder } from './payments/index';
// @ts-ignore
import { ProductsRequestBuilderRequestsMetadata, type ProductsRequestBuilder } from './products/index';
// @ts-ignore
import { QuotesRequestBuilderNavigationMetadata, QuotesRequestBuilderRequestsMetadata, type QuotesRequestBuilder } from './quotes/index';
// @ts-ignore
import { ShipmentsRequestBuilderRequestsMetadata, type ShipmentsRequestBuilder } from './shipments/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The accounts property
     */
    get accounts(): AccountsRequestBuilder;
    /**
     * The customers property
     */
    get customers(): CustomersRequestBuilder;
    /**
     * The inventory property
     */
    get inventory(): InventoryRequestBuilder;
    /**
     * The orders property
     */
    get orders(): OrdersRequestBuilder;
    /**
     * The payments property
     */
    get payments(): PaymentsRequestBuilder;
    /**
     * The products property
     */
    get products(): ProductsRequestBuilder;
    /**
     * The quotes property
     */
    get quotes(): QuotesRequestBuilder;
    /**
     * The shipments property
     */
    get shipments(): ShipmentsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    accounts: {
        navigationMetadata: AccountsRequestBuilderNavigationMetadata,
    },
    customers: {
        requestsMetadata: CustomersRequestBuilderRequestsMetadata,
        navigationMetadata: CustomersRequestBuilderNavigationMetadata,
    },
    inventory: {
        navigationMetadata: InventoryRequestBuilderNavigationMetadata,
    },
    orders: {
        requestsMetadata: OrdersRequestBuilderRequestsMetadata,
        navigationMetadata: OrdersRequestBuilderNavigationMetadata,
    },
    payments: {
        requestsMetadata: PaymentsRequestBuilderRequestsMetadata,
        navigationMetadata: PaymentsRequestBuilderNavigationMetadata,
    },
    products: {
        requestsMetadata: ProductsRequestBuilderRequestsMetadata,
    },
    quotes: {
        requestsMetadata: QuotesRequestBuilderRequestsMetadata,
        navigationMetadata: QuotesRequestBuilderNavigationMetadata,
    },
    shipments: {
        requestsMetadata: ShipmentsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
