// <auto-generated/>
#pragma warning disable CS0618
using EcommerceDDD.ServiceClients.ApiGateway.Api.Customers.Item.Credit;
using EcommerceDDD.ServiceClients.ApiGateway.Api.Customers.Item.Details;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EcommerceDDD.ServiceClients.ApiGateway.Api.Customers.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\customers\{customerId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCustomerItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The credit property</summary>
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.Customers.Item.Credit.CreditRequestBuilder Credit
        {
            get => new global::EcommerceDDD.ServiceClients.ApiGateway.Api.Customers.Item.Credit.CreditRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The details property</summary>
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.Customers.Item.Details.DetailsRequestBuilder Details
        {
            get => new global::EcommerceDDD.ServiceClients.ApiGateway.Api.Customers.Item.Details.DetailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.ApiGateway.Api.Customers.Item.WithCustomerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCustomerItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/customers/{customerId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.ApiGateway.Api.Customers.Item.WithCustomerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCustomerItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/customers/{customerId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
