/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ApiRequestBuilderNavigationMetadata, type ApiRequestBuilder } from './api/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /inventoryManagement
 */
export interface InventoryManagementRequestBuilder extends BaseRequestBuilder<InventoryManagementRequestBuilder> {
    /**
     * The api property
     */
    get api(): ApiRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const InventoryManagementRequestBuilderUriTemplate = "{+baseurl}/inventoryManagement";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const InventoryManagementRequestBuilderNavigationMetadata: Record<Exclude<keyof InventoryManagementRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    api: {
        navigationMetadata: ApiRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
