/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CustomersRequestBuilderNavigationMetadata, CustomersRequestBuilderRequestsMetadata, type CustomersRequestBuilder } from './customers/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /customerManagement/api/v2
 */
export interface V2RequestBuilder extends BaseRequestBuilder<V2RequestBuilder> {
    /**
     * The customers property
     */
    get customers(): CustomersRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const V2RequestBuilderUriTemplate = "{+baseurl}/customerManagement/api/v2";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const V2RequestBuilderNavigationMetadata: Record<Exclude<keyof V2RequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    customers: {
        requestsMetadata: CustomersRequestBuilderRequestsMetadata,
        navigationMetadata: CustomersRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
