/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createInventoryStockUnitViewModelIListApiResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeIncreaseQuantityInStockRequest, serializeInventoryStockUnitViewModelIListApiResponse, type IncreaseQuantityInStockRequest, type InventoryStockUnitViewModelIListApiResponse, type ProblemDetails } from '../../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/inventory/increase-stock-quantity/{productId}
 */
export interface WithProductItemRequestBuilder extends BaseRequestBuilder<WithProductItemRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InventoryStockUnitViewModelIListApiResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     put(body: IncreaseQuantityInStockRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<InventoryStockUnitViewModelIListApiResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: IncreaseQuantityInStockRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithProductItemRequestBuilderUriTemplate = "{+baseurl}/api/inventory/increase-stock-quantity/{productId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithProductItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: WithProductItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createInventoryStockUnitViewModelIListApiResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeIncreaseQuantityInStockRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
