/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AddQuoteItemRequest extends Parsable {
    /**
     * The productId property
     */
    productId?: Guid | null;
    /**
     * The quantity property
     */
    quantity?: number | null;
}
export interface CancelPaymentRequest extends Parsable {
    /**
     * The paymentCancellationReason property
     */
    paymentCancellationReason?: number | null;
}
export interface CheckProductsInStockRequest extends Parsable {
    /**
     * The productIds property
     */
    productIds?: Guid[] | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AddQuoteItemRequest}
 */
// @ts-ignore
export function createAddQuoteItemRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAddQuoteItemRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CancelPaymentRequest}
 */
// @ts-ignore
export function createCancelPaymentRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCancelPaymentRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CheckProductsInStockRequest}
 */
// @ts-ignore
export function createCheckProductsInStockRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCheckProductsInStockRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreditLimitModelApiResponse}
 */
// @ts-ignore
export function createCreditLimitModelApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreditLimitModelApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreditLimitModel}
 */
// @ts-ignore
export function createCreditLimitModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreditLimitModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CustomerDetailsApiResponse}
 */
// @ts-ignore
export function createCustomerDetailsApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCustomerDetailsApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CustomerDetails}
 */
// @ts-ignore
export function createCustomerDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCustomerDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DecreaseQuantityInStockRequest}
 */
// @ts-ignore
export function createDecreaseQuantityInStockRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDecreaseQuantityInStockRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GetProductsRequest}
 */
// @ts-ignore
export function createGetProductsRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetProductsRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IEventHistory}
 */
// @ts-ignore
export function createIEventHistoryFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIEventHistory;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IEventHistoryIListApiResponse}
 */
// @ts-ignore
export function createIEventHistoryIListApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIEventHistoryIListApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InventoryStockUnitEventHistory}
 */
// @ts-ignore
export function createInventoryStockUnitEventHistoryFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInventoryStockUnitEventHistory;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InventoryStockUnitEventHistoryIListApiResponse}
 */
// @ts-ignore
export function createInventoryStockUnitEventHistoryIListApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInventoryStockUnitEventHistoryIListApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InventoryStockUnitViewModel}
 */
// @ts-ignore
export function createInventoryStockUnitViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInventoryStockUnitViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InventoryStockUnitViewModelIListApiResponse}
 */
// @ts-ignore
export function createInventoryStockUnitViewModelIListApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInventoryStockUnitViewModelIListApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginRequest}
 */
// @ts-ignore
export function createLoginRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginResult}
 */
// @ts-ignore
export function createLoginResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OpenQuoteRequest}
 */
// @ts-ignore
export function createOpenQuoteRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOpenQuoteRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OrderLineViewModel}
 */
// @ts-ignore
export function createOrderLineViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOrderLineViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OrderViewModel}
 */
// @ts-ignore
export function createOrderViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOrderViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OrderViewModelIListApiResponse}
 */
// @ts-ignore
export function createOrderViewModelIListApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOrderViewModelIListApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaymentRequest}
 */
// @ts-ignore
export function createPaymentRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaymentRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProblemDetails}
 */
// @ts-ignore
export function createProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProductItemRequest}
 */
// @ts-ignore
export function createProductItemRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProductItemRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProductViewModel}
 */
// @ts-ignore
export function createProductViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProductViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProductViewModelIListApiResponse}
 */
// @ts-ignore
export function createProductViewModelIListApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProductViewModelIListApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QuoteItemViewModel}
 */
// @ts-ignore
export function createQuoteItemViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQuoteItemViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QuoteViewModelApiResponse}
 */
// @ts-ignore
export function createQuoteViewModelApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQuoteViewModelApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QuoteViewModel}
 */
// @ts-ignore
export function createQuoteViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQuoteViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RegisterCustomerRequest}
 */
// @ts-ignore
export function createRegisterCustomerRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRegisterCustomerRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RegisterUserRequest}
 */
// @ts-ignore
export function createRegisterUserRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRegisterUserRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ShipOrderRequest}
 */
// @ts-ignore
export function createShipOrderRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoShipOrderRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateCustomerRequest}
 */
// @ts-ignore
export function createUpdateCustomerRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateCustomerRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateOrderStatusRequest}
 */
// @ts-ignore
export function createUpdateOrderStatusRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateOrderStatusRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UserRegisteredResult}
 */
// @ts-ignore
export function createUserRegisteredResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUserRegisteredResult;
}
export interface CreditLimitModel extends Parsable {
    /**
     * The creditLimit property
     */
    creditLimit?: number | null;
    /**
     * The customerId property
     */
    customerId?: Guid | null;
}
export interface CreditLimitModelApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: CreditLimitModel | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface CustomerDetails extends Parsable {
    /**
     * The creditLimit property
     */
    creditLimit?: number | null;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The shippingAddress property
     */
    shippingAddress?: string | null;
}
export interface CustomerDetailsApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: CustomerDetails | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface DecreaseQuantityInStockRequest extends Parsable {
    /**
     * The decreasedQuantity property
     */
    decreasedQuantity?: number | null;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAddQuoteItemRequest(addQuoteItemRequest: Partial<AddQuoteItemRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "productId": n => { addQuoteItemRequest.productId = n.getGuidValue(); },
        "quantity": n => { addQuoteItemRequest.quantity = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCancelPaymentRequest(cancelPaymentRequest: Partial<CancelPaymentRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "paymentCancellationReason": n => { cancelPaymentRequest.paymentCancellationReason = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCheckProductsInStockRequest(checkProductsInStockRequest: Partial<CheckProductsInStockRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "productIds": n => { checkProductsInStockRequest.productIds = n.getCollectionOfPrimitiveValues<Guid>(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreditLimitModel(creditLimitModel: Partial<CreditLimitModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "creditLimit": n => { creditLimitModel.creditLimit = n.getNumberValue(); },
        "customerId": n => { creditLimitModel.customerId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreditLimitModelApiResponse(creditLimitModelApiResponse: Partial<CreditLimitModelApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { creditLimitModelApiResponse.data = n.getObjectValue<CreditLimitModel>(createCreditLimitModelFromDiscriminatorValue); },
        "message": n => { creditLimitModelApiResponse.message = n.getStringValue(); },
        "success": n => { creditLimitModelApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCustomerDetails(customerDetails: Partial<CustomerDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "creditLimit": n => { customerDetails.creditLimit = n.getNumberValue(); },
        "email": n => { customerDetails.email = n.getStringValue(); },
        "id": n => { customerDetails.id = n.getGuidValue(); },
        "name": n => { customerDetails.name = n.getStringValue(); },
        "shippingAddress": n => { customerDetails.shippingAddress = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCustomerDetailsApiResponse(customerDetailsApiResponse: Partial<CustomerDetailsApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { customerDetailsApiResponse.data = n.getObjectValue<CustomerDetails>(createCustomerDetailsFromDiscriminatorValue); },
        "message": n => { customerDetailsApiResponse.message = n.getStringValue(); },
        "success": n => { customerDetailsApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDecreaseQuantityInStockRequest(decreaseQuantityInStockRequest: Partial<DecreaseQuantityInStockRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "decreasedQuantity": n => { decreaseQuantityInStockRequest.decreasedQuantity = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGetProductsRequest(getProductsRequest: Partial<GetProductsRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "currencyCode": n => { getProductsRequest.currencyCode = n.getStringValue(); },
        "productIds": n => { getProductsRequest.productIds = n.getCollectionOfPrimitiveValues<Guid>(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIEventHistory(iEventHistory: Partial<IEventHistory> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "aggregateId": n => { iEventHistory.aggregateId = n.getGuidValue(); },
        "eventData": n => { iEventHistory.eventData = n.getStringValue(); },
        "eventTypeName": n => { iEventHistory.eventTypeName = n.getStringValue(); },
        "id": n => { iEventHistory.id = n.getGuidValue(); },
        "timestamp": n => { iEventHistory.timestamp = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIEventHistoryIListApiResponse(iEventHistoryIListApiResponse: Partial<IEventHistoryIListApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { iEventHistoryIListApiResponse.data = n.getCollectionOfObjectValues<IEventHistory>(createIEventHistoryFromDiscriminatorValue); },
        "message": n => { iEventHistoryIListApiResponse.message = n.getStringValue(); },
        "success": n => { iEventHistoryIListApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInventoryStockUnitEventHistory(inventoryStockUnitEventHistory: Partial<InventoryStockUnitEventHistory> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "aggregateId": n => { inventoryStockUnitEventHistory.aggregateId = n.getGuidValue(); },
        "eventData": n => { inventoryStockUnitEventHistory.eventData = n.getStringValue(); },
        "eventTypeName": n => { inventoryStockUnitEventHistory.eventTypeName = n.getStringValue(); },
        "id": n => { inventoryStockUnitEventHistory.id = n.getGuidValue(); },
        "timestamp": n => { inventoryStockUnitEventHistory.timestamp = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInventoryStockUnitEventHistoryIListApiResponse(inventoryStockUnitEventHistoryIListApiResponse: Partial<InventoryStockUnitEventHistoryIListApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { inventoryStockUnitEventHistoryIListApiResponse.data = n.getCollectionOfObjectValues<InventoryStockUnitEventHistory>(createInventoryStockUnitEventHistoryFromDiscriminatorValue); },
        "message": n => { inventoryStockUnitEventHistoryIListApiResponse.message = n.getStringValue(); },
        "success": n => { inventoryStockUnitEventHistoryIListApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInventoryStockUnitViewModel(inventoryStockUnitViewModel: Partial<InventoryStockUnitViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "inventoryStockUnitId": n => { inventoryStockUnitViewModel.inventoryStockUnitId = n.getGuidValue(); },
        "productId": n => { inventoryStockUnitViewModel.productId = n.getGuidValue(); },
        "quantityInStock": n => { inventoryStockUnitViewModel.quantityInStock = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInventoryStockUnitViewModelIListApiResponse(inventoryStockUnitViewModelIListApiResponse: Partial<InventoryStockUnitViewModelIListApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { inventoryStockUnitViewModelIListApiResponse.data = n.getCollectionOfObjectValues<InventoryStockUnitViewModel>(createInventoryStockUnitViewModelFromDiscriminatorValue); },
        "message": n => { inventoryStockUnitViewModelIListApiResponse.message = n.getStringValue(); },
        "success": n => { inventoryStockUnitViewModelIListApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginRequest(loginRequest: Partial<LoginRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { loginRequest.email = n.getStringValue(); },
        "password": n => { loginRequest.password = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginResult(loginResult: Partial<LoginResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "accessToken": n => { loginResult.accessToken = n.getStringValue(); },
        "errorDescription": n => { loginResult.errorDescription = n.getStringValue(); },
        "identityToken": n => { loginResult.identityToken = n.getStringValue(); },
        "refreshToken": n => { loginResult.refreshToken = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOpenQuoteRequest(openQuoteRequest: Partial<OpenQuoteRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "currencyCode": n => { openQuoteRequest.currencyCode = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOrderLineViewModel(orderLineViewModel: Partial<OrderLineViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "productId": n => { orderLineViewModel.productId = n.getGuidValue(); },
        "productName": n => { orderLineViewModel.productName = n.getStringValue(); },
        "quantity": n => { orderLineViewModel.quantity = n.getNumberValue(); },
        "unitPrice": n => { orderLineViewModel.unitPrice = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOrderViewModel(orderViewModel: Partial<OrderViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { orderViewModel.createdAt = n.getDateValue(); },
        "currencySymbol": n => { orderViewModel.currencySymbol = n.getStringValue(); },
        "customerId": n => { orderViewModel.customerId = n.getGuidValue(); },
        "orderId": n => { orderViewModel.orderId = n.getGuidValue(); },
        "orderLines": n => { orderViewModel.orderLines = n.getCollectionOfObjectValues<OrderLineViewModel>(createOrderLineViewModelFromDiscriminatorValue); },
        "quoteId": n => { orderViewModel.quoteId = n.getGuidValue(); },
        "statusCode": n => { orderViewModel.statusCode = n.getNumberValue(); },
        "statusText": n => { orderViewModel.statusText = n.getStringValue(); },
        "totalPrice": n => { orderViewModel.totalPrice = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOrderViewModelIListApiResponse(orderViewModelIListApiResponse: Partial<OrderViewModelIListApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { orderViewModelIListApiResponse.data = n.getCollectionOfObjectValues<OrderViewModel>(createOrderViewModelFromDiscriminatorValue); },
        "message": n => { orderViewModelIListApiResponse.message = n.getStringValue(); },
        "success": n => { orderViewModelIListApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaymentRequest(paymentRequest: Partial<PaymentRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "currencyCode": n => { paymentRequest.currencyCode = n.getStringValue(); },
        "customerId": n => { paymentRequest.customerId = n.getGuidValue(); },
        "orderId": n => { paymentRequest.orderId = n.getGuidValue(); },
        "productItems": n => { paymentRequest.productItems = n.getCollectionOfObjectValues<ProductItemRequest>(createProductItemRequestFromDiscriminatorValue); },
        "totalAmount": n => { paymentRequest.totalAmount = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProblemDetails(problemDetails: Partial<ProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { problemDetails.detail = n.getStringValue(); },
        "instance": n => { problemDetails.instance = n.getStringValue(); },
        "status": n => { problemDetails.status = n.getNumberValue(); },
        "title": n => { problemDetails.title = n.getStringValue(); },
        "type": n => { problemDetails.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProductItemRequest(productItemRequest: Partial<ProductItemRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "productId": n => { productItemRequest.productId = n.getGuidValue(); },
        "productName": n => { productItemRequest.productName = n.getStringValue(); },
        "quantity": n => { productItemRequest.quantity = n.getNumberValue(); },
        "unitPrice": n => { productItemRequest.unitPrice = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProductViewModel(productViewModel: Partial<ProductViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "category": n => { productViewModel.category = n.getStringValue(); },
        "currencySymbol": n => { productViewModel.currencySymbol = n.getStringValue(); },
        "description": n => { productViewModel.description = n.getStringValue(); },
        "imageUrl": n => { productViewModel.imageUrl = n.getStringValue(); },
        "name": n => { productViewModel.name = n.getStringValue(); },
        "price": n => { productViewModel.price = n.getNumberValue(); },
        "productId": n => { productViewModel.productId = n.getGuidValue(); },
        "quantityAddedToCart": n => { productViewModel.quantityAddedToCart = n.getNumberValue(); },
        "quantityInStock": n => { productViewModel.quantityInStock = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProductViewModelIListApiResponse(productViewModelIListApiResponse: Partial<ProductViewModelIListApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { productViewModelIListApiResponse.data = n.getCollectionOfObjectValues<ProductViewModel>(createProductViewModelFromDiscriminatorValue); },
        "message": n => { productViewModelIListApiResponse.message = n.getStringValue(); },
        "success": n => { productViewModelIListApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQuoteItemViewModel(quoteItemViewModel: Partial<QuoteItemViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "currencySymbol": n => { quoteItemViewModel.currencySymbol = n.getStringValue(); },
        "productId": n => { quoteItemViewModel.productId = n.getGuidValue(); },
        "productName": n => { quoteItemViewModel.productName = n.getStringValue(); },
        "quantity": n => { quoteItemViewModel.quantity = n.getNumberValue(); },
        "unitPrice": n => { quoteItemViewModel.unitPrice = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQuoteViewModel(quoteViewModel: Partial<QuoteViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { quoteViewModel.createdAt = n.getDateValue(); },
        "currencyCode": n => { quoteViewModel.currencyCode = n.getStringValue(); },
        "currencySymbol": n => { quoteViewModel.currencySymbol = n.getStringValue(); },
        "customerId": n => { quoteViewModel.customerId = n.getGuidValue(); },
        "items": n => { quoteViewModel.items = n.getCollectionOfObjectValues<QuoteItemViewModel>(createQuoteItemViewModelFromDiscriminatorValue); },
        "quoteId": n => { quoteViewModel.quoteId = n.getGuidValue(); },
        "quoteStatus": n => { quoteViewModel.quoteStatus = n.getStringValue(); },
        "totalPrice": n => { quoteViewModel.totalPrice = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQuoteViewModelApiResponse(quoteViewModelApiResponse: Partial<QuoteViewModelApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { quoteViewModelApiResponse.data = n.getObjectValue<QuoteViewModel>(createQuoteViewModelFromDiscriminatorValue); },
        "message": n => { quoteViewModelApiResponse.message = n.getStringValue(); },
        "success": n => { quoteViewModelApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRegisterCustomerRequest(registerCustomerRequest: Partial<RegisterCustomerRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "creditLimit": n => { registerCustomerRequest.creditLimit = n.getNumberValue(); },
        "email": n => { registerCustomerRequest.email = n.getStringValue(); },
        "name": n => { registerCustomerRequest.name = n.getStringValue(); },
        "password": n => { registerCustomerRequest.password = n.getStringValue(); },
        "passwordConfirm": n => { registerCustomerRequest.passwordConfirm = n.getStringValue(); },
        "shippingAddress": n => { registerCustomerRequest.shippingAddress = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRegisterUserRequest(registerUserRequest: Partial<RegisterUserRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "customerId": n => { registerUserRequest.customerId = n.getGuidValue(); },
        "email": n => { registerUserRequest.email = n.getStringValue(); },
        "password": n => { registerUserRequest.password = n.getStringValue(); },
        "passwordConfirm": n => { registerUserRequest.passwordConfirm = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoShipOrderRequest(shipOrderRequest: Partial<ShipOrderRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "orderId": n => { shipOrderRequest.orderId = n.getGuidValue(); },
        "productItems": n => { shipOrderRequest.productItems = n.getCollectionOfObjectValues<ProductItemRequest>(createProductItemRequestFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateCustomerRequest(updateCustomerRequest: Partial<UpdateCustomerRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "creditLimit": n => { updateCustomerRequest.creditLimit = n.getNumberValue(); },
        "name": n => { updateCustomerRequest.name = n.getStringValue(); },
        "shippingAddress": n => { updateCustomerRequest.shippingAddress = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateOrderStatusRequest(updateOrderStatusRequest: Partial<UpdateOrderStatusRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "customerId": n => { updateOrderStatusRequest.customerId = n.getGuidValue(); },
        "orderId": n => { updateOrderStatusRequest.orderId = n.getGuidValue(); },
        "orderStatusCode": n => { updateOrderStatusRequest.orderStatusCode = n.getNumberValue(); },
        "orderStatusText": n => { updateOrderStatusRequest.orderStatusText = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUserRegisteredResult(userRegisteredResult: Partial<UserRegisteredResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "succeeded": n => { userRegisteredResult.succeeded = n.getBooleanValue(); },
        "userId": n => { userRegisteredResult.userId = n.getStringValue(); },
    }
}
export interface GetProductsRequest extends Parsable {
    /**
     * The currencyCode property
     */
    currencyCode?: string | null;
    /**
     * The productIds property
     */
    productIds?: Guid[] | null;
}
export interface IEventHistory extends Parsable {
    /**
     * The aggregateId property
     */
    aggregateId?: Guid | null;
    /**
     * The eventData property
     */
    eventData?: string | null;
    /**
     * The eventTypeName property
     */
    eventTypeName?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The timestamp property
     */
    timestamp?: Date | null;
}
export interface IEventHistoryIListApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: IEventHistory[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface InventoryStockUnitEventHistory extends Parsable {
    /**
     * The aggregateId property
     */
    aggregateId?: Guid | null;
    /**
     * The eventData property
     */
    eventData?: string | null;
    /**
     * The eventTypeName property
     */
    eventTypeName?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The timestamp property
     */
    timestamp?: Date | null;
}
export interface InventoryStockUnitEventHistoryIListApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: InventoryStockUnitEventHistory[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface InventoryStockUnitViewModel extends Parsable {
    /**
     * The inventoryStockUnitId property
     */
    inventoryStockUnitId?: Guid | null;
    /**
     * The productId property
     */
    productId?: Guid | null;
    /**
     * The quantityInStock property
     */
    quantityInStock?: number | null;
}
export interface InventoryStockUnitViewModelIListApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: InventoryStockUnitViewModel[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface LoginRequest extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
}
export interface LoginResult extends Parsable {
    /**
     * The accessToken property
     */
    accessToken?: string | null;
    /**
     * The errorDescription property
     */
    errorDescription?: string | null;
    /**
     * The identityToken property
     */
    identityToken?: string | null;
    /**
     * The refreshToken property
     */
    refreshToken?: string | null;
}
export interface OpenQuoteRequest extends Parsable {
    /**
     * The currencyCode property
     */
    currencyCode?: string | null;
}
export interface OrderLineViewModel extends Parsable {
    /**
     * The productId property
     */
    productId?: Guid | null;
    /**
     * The productName property
     */
    productName?: string | null;
    /**
     * The quantity property
     */
    quantity?: number | null;
    /**
     * The unitPrice property
     */
    unitPrice?: number | null;
}
export interface OrderViewModel extends Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The currencySymbol property
     */
    currencySymbol?: string | null;
    /**
     * The customerId property
     */
    customerId?: Guid | null;
    /**
     * The orderId property
     */
    orderId?: Guid | null;
    /**
     * The orderLines property
     */
    orderLines?: OrderLineViewModel[] | null;
    /**
     * The quoteId property
     */
    quoteId?: Guid | null;
    /**
     * The statusCode property
     */
    statusCode?: number | null;
    /**
     * The statusText property
     */
    statusText?: string | null;
    /**
     * The totalPrice property
     */
    totalPrice?: number | null;
}
export interface OrderViewModelIListApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: OrderViewModel[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface PaymentRequest extends Parsable {
    /**
     * The currencyCode property
     */
    currencyCode?: string | null;
    /**
     * The customerId property
     */
    customerId?: Guid | null;
    /**
     * The orderId property
     */
    orderId?: Guid | null;
    /**
     * The productItems property
     */
    productItems?: ProductItemRequest[] | null;
    /**
     * The totalAmount property
     */
    totalAmount?: number | null;
}
export interface ProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface ProductItemRequest extends Parsable {
    /**
     * The productId property
     */
    productId?: Guid | null;
    /**
     * The productName property
     */
    productName?: string | null;
    /**
     * The quantity property
     */
    quantity?: number | null;
    /**
     * The unitPrice property
     */
    unitPrice?: number | null;
}
export interface ProductViewModel extends Parsable {
    /**
     * The category property
     */
    category?: string | null;
    /**
     * The currencySymbol property
     */
    currencySymbol?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The imageUrl property
     */
    imageUrl?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The price property
     */
    price?: number | null;
    /**
     * The productId property
     */
    productId?: Guid | null;
    /**
     * The quantityAddedToCart property
     */
    quantityAddedToCart?: number | null;
    /**
     * The quantityInStock property
     */
    quantityInStock?: number | null;
}
export interface ProductViewModelIListApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: ProductViewModel[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface QuoteItemViewModel extends Parsable {
    /**
     * The currencySymbol property
     */
    currencySymbol?: string | null;
    /**
     * The productId property
     */
    productId?: Guid | null;
    /**
     * The productName property
     */
    productName?: string | null;
    /**
     * The quantity property
     */
    quantity?: number | null;
    /**
     * The unitPrice property
     */
    unitPrice?: number | null;
}
export interface QuoteViewModel extends Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The currencyCode property
     */
    currencyCode?: string | null;
    /**
     * The currencySymbol property
     */
    currencySymbol?: string | null;
    /**
     * The customerId property
     */
    customerId?: Guid | null;
    /**
     * The items property
     */
    items?: QuoteItemViewModel[] | null;
    /**
     * The quoteId property
     */
    quoteId?: Guid | null;
    /**
     * The quoteStatus property
     */
    quoteStatus?: string | null;
    /**
     * The totalPrice property
     */
    totalPrice?: number | null;
}
export interface QuoteViewModelApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: QuoteViewModel | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface RegisterCustomerRequest extends Parsable {
    /**
     * The creditLimit property
     */
    creditLimit?: number | null;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The password property
     */
    password?: string | null;
    /**
     * The passwordConfirm property
     */
    passwordConfirm?: string | null;
    /**
     * The shippingAddress property
     */
    shippingAddress?: string | null;
}
export interface RegisterUserRequest extends Parsable {
    /**
     * The customerId property
     */
    customerId?: Guid | null;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
    /**
     * The passwordConfirm property
     */
    passwordConfirm?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAddQuoteItemRequest(writer: SerializationWriter, addQuoteItemRequest: Partial<AddQuoteItemRequest> | undefined | null = {}) : void {
    if (addQuoteItemRequest) {
        writer.writeGuidValue("productId", addQuoteItemRequest.productId);
        writer.writeNumberValue("quantity", addQuoteItemRequest.quantity);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCancelPaymentRequest(writer: SerializationWriter, cancelPaymentRequest: Partial<CancelPaymentRequest> | undefined | null = {}) : void {
    if (cancelPaymentRequest) {
        writer.writeNumberValue("paymentCancellationReason", cancelPaymentRequest.paymentCancellationReason);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCheckProductsInStockRequest(writer: SerializationWriter, checkProductsInStockRequest: Partial<CheckProductsInStockRequest> | undefined | null = {}) : void {
    if (checkProductsInStockRequest) {
        writer.writeCollectionOfPrimitiveValues<Guid>("productIds", checkProductsInStockRequest.productIds);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreditLimitModel(writer: SerializationWriter, creditLimitModel: Partial<CreditLimitModel> | undefined | null = {}) : void {
    if (creditLimitModel) {
        writer.writeNumberValue("creditLimit", creditLimitModel.creditLimit);
        writer.writeGuidValue("customerId", creditLimitModel.customerId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreditLimitModelApiResponse(writer: SerializationWriter, creditLimitModelApiResponse: Partial<CreditLimitModelApiResponse> | undefined | null = {}) : void {
    if (creditLimitModelApiResponse) {
        writer.writeObjectValue<CreditLimitModel>("data", creditLimitModelApiResponse.data, serializeCreditLimitModel);
        writer.writeStringValue("message", creditLimitModelApiResponse.message);
        writer.writeBooleanValue("success", creditLimitModelApiResponse.success);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCustomerDetails(writer: SerializationWriter, customerDetails: Partial<CustomerDetails> | undefined | null = {}) : void {
    if (customerDetails) {
        writer.writeNumberValue("creditLimit", customerDetails.creditLimit);
        writer.writeStringValue("email", customerDetails.email);
        writer.writeGuidValue("id", customerDetails.id);
        writer.writeStringValue("name", customerDetails.name);
        writer.writeStringValue("shippingAddress", customerDetails.shippingAddress);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCustomerDetailsApiResponse(writer: SerializationWriter, customerDetailsApiResponse: Partial<CustomerDetailsApiResponse> | undefined | null = {}) : void {
    if (customerDetailsApiResponse) {
        writer.writeObjectValue<CustomerDetails>("data", customerDetailsApiResponse.data, serializeCustomerDetails);
        writer.writeStringValue("message", customerDetailsApiResponse.message);
        writer.writeBooleanValue("success", customerDetailsApiResponse.success);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDecreaseQuantityInStockRequest(writer: SerializationWriter, decreaseQuantityInStockRequest: Partial<DecreaseQuantityInStockRequest> | undefined | null = {}) : void {
    if (decreaseQuantityInStockRequest) {
        writer.writeNumberValue("decreasedQuantity", decreaseQuantityInStockRequest.decreasedQuantity);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGetProductsRequest(writer: SerializationWriter, getProductsRequest: Partial<GetProductsRequest> | undefined | null = {}) : void {
    if (getProductsRequest) {
        writer.writeStringValue("currencyCode", getProductsRequest.currencyCode);
        writer.writeCollectionOfPrimitiveValues<Guid>("productIds", getProductsRequest.productIds);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIEventHistory(writer: SerializationWriter, iEventHistory: Partial<IEventHistory> | undefined | null = {}) : void {
    if (iEventHistory) {
        writer.writeGuidValue("aggregateId", iEventHistory.aggregateId);
        writer.writeStringValue("eventData", iEventHistory.eventData);
        writer.writeStringValue("eventTypeName", iEventHistory.eventTypeName);
        writer.writeGuidValue("id", iEventHistory.id);
        writer.writeDateValue("timestamp", iEventHistory.timestamp);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIEventHistoryIListApiResponse(writer: SerializationWriter, iEventHistoryIListApiResponse: Partial<IEventHistoryIListApiResponse> | undefined | null = {}) : void {
    if (iEventHistoryIListApiResponse) {
        writer.writeCollectionOfObjectValues<IEventHistory>("data", iEventHistoryIListApiResponse.data, serializeIEventHistory);
        writer.writeStringValue("message", iEventHistoryIListApiResponse.message);
        writer.writeBooleanValue("success", iEventHistoryIListApiResponse.success);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInventoryStockUnitEventHistory(writer: SerializationWriter, inventoryStockUnitEventHistory: Partial<InventoryStockUnitEventHistory> | undefined | null = {}) : void {
    if (inventoryStockUnitEventHistory) {
        writer.writeGuidValue("aggregateId", inventoryStockUnitEventHistory.aggregateId);
        writer.writeStringValue("eventData", inventoryStockUnitEventHistory.eventData);
        writer.writeStringValue("eventTypeName", inventoryStockUnitEventHistory.eventTypeName);
        writer.writeGuidValue("id", inventoryStockUnitEventHistory.id);
        writer.writeDateValue("timestamp", inventoryStockUnitEventHistory.timestamp);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInventoryStockUnitEventHistoryIListApiResponse(writer: SerializationWriter, inventoryStockUnitEventHistoryIListApiResponse: Partial<InventoryStockUnitEventHistoryIListApiResponse> | undefined | null = {}) : void {
    if (inventoryStockUnitEventHistoryIListApiResponse) {
        writer.writeCollectionOfObjectValues<InventoryStockUnitEventHistory>("data", inventoryStockUnitEventHistoryIListApiResponse.data, serializeInventoryStockUnitEventHistory);
        writer.writeStringValue("message", inventoryStockUnitEventHistoryIListApiResponse.message);
        writer.writeBooleanValue("success", inventoryStockUnitEventHistoryIListApiResponse.success);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInventoryStockUnitViewModel(writer: SerializationWriter, inventoryStockUnitViewModel: Partial<InventoryStockUnitViewModel> | undefined | null = {}) : void {
    if (inventoryStockUnitViewModel) {
        writer.writeGuidValue("inventoryStockUnitId", inventoryStockUnitViewModel.inventoryStockUnitId);
        writer.writeGuidValue("productId", inventoryStockUnitViewModel.productId);
        writer.writeNumberValue("quantityInStock", inventoryStockUnitViewModel.quantityInStock);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInventoryStockUnitViewModelIListApiResponse(writer: SerializationWriter, inventoryStockUnitViewModelIListApiResponse: Partial<InventoryStockUnitViewModelIListApiResponse> | undefined | null = {}) : void {
    if (inventoryStockUnitViewModelIListApiResponse) {
        writer.writeCollectionOfObjectValues<InventoryStockUnitViewModel>("data", inventoryStockUnitViewModelIListApiResponse.data, serializeInventoryStockUnitViewModel);
        writer.writeStringValue("message", inventoryStockUnitViewModelIListApiResponse.message);
        writer.writeBooleanValue("success", inventoryStockUnitViewModelIListApiResponse.success);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginRequest(writer: SerializationWriter, loginRequest: Partial<LoginRequest> | undefined | null = {}) : void {
    if (loginRequest) {
        writer.writeStringValue("email", loginRequest.email);
        writer.writeStringValue("password", loginRequest.password);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginResult(writer: SerializationWriter, loginResult: Partial<LoginResult> | undefined | null = {}) : void {
    if (loginResult) {
        writer.writeStringValue("accessToken", loginResult.accessToken);
        writer.writeStringValue("errorDescription", loginResult.errorDescription);
        writer.writeStringValue("identityToken", loginResult.identityToken);
        writer.writeStringValue("refreshToken", loginResult.refreshToken);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOpenQuoteRequest(writer: SerializationWriter, openQuoteRequest: Partial<OpenQuoteRequest> | undefined | null = {}) : void {
    if (openQuoteRequest) {
        writer.writeStringValue("currencyCode", openQuoteRequest.currencyCode);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOrderLineViewModel(writer: SerializationWriter, orderLineViewModel: Partial<OrderLineViewModel> | undefined | null = {}) : void {
    if (orderLineViewModel) {
        writer.writeGuidValue("productId", orderLineViewModel.productId);
        writer.writeStringValue("productName", orderLineViewModel.productName);
        writer.writeNumberValue("quantity", orderLineViewModel.quantity);
        writer.writeNumberValue("unitPrice", orderLineViewModel.unitPrice);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOrderViewModel(writer: SerializationWriter, orderViewModel: Partial<OrderViewModel> | undefined | null = {}) : void {
    if (orderViewModel) {
        writer.writeDateValue("createdAt", orderViewModel.createdAt);
        writer.writeStringValue("currencySymbol", orderViewModel.currencySymbol);
        writer.writeGuidValue("customerId", orderViewModel.customerId);
        writer.writeGuidValue("orderId", orderViewModel.orderId);
        writer.writeCollectionOfObjectValues<OrderLineViewModel>("orderLines", orderViewModel.orderLines, serializeOrderLineViewModel);
        writer.writeGuidValue("quoteId", orderViewModel.quoteId);
        writer.writeNumberValue("statusCode", orderViewModel.statusCode);
        writer.writeStringValue("statusText", orderViewModel.statusText);
        writer.writeNumberValue("totalPrice", orderViewModel.totalPrice);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOrderViewModelIListApiResponse(writer: SerializationWriter, orderViewModelIListApiResponse: Partial<OrderViewModelIListApiResponse> | undefined | null = {}) : void {
    if (orderViewModelIListApiResponse) {
        writer.writeCollectionOfObjectValues<OrderViewModel>("data", orderViewModelIListApiResponse.data, serializeOrderViewModel);
        writer.writeStringValue("message", orderViewModelIListApiResponse.message);
        writer.writeBooleanValue("success", orderViewModelIListApiResponse.success);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaymentRequest(writer: SerializationWriter, paymentRequest: Partial<PaymentRequest> | undefined | null = {}) : void {
    if (paymentRequest) {
        writer.writeStringValue("currencyCode", paymentRequest.currencyCode);
        writer.writeGuidValue("customerId", paymentRequest.customerId);
        writer.writeGuidValue("orderId", paymentRequest.orderId);
        writer.writeCollectionOfObjectValues<ProductItemRequest>("productItems", paymentRequest.productItems, serializeProductItemRequest);
        writer.writeNumberValue("totalAmount", paymentRequest.totalAmount);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProblemDetails(writer: SerializationWriter, problemDetails: Partial<ProblemDetails> | undefined | null = {}) : void {
    if (problemDetails) {
        writer.writeStringValue("detail", problemDetails.detail);
        writer.writeStringValue("instance", problemDetails.instance);
        writer.writeNumberValue("status", problemDetails.status);
        writer.writeStringValue("title", problemDetails.title);
        writer.writeStringValue("type", problemDetails.type);
        writer.writeAdditionalData(problemDetails.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProductItemRequest(writer: SerializationWriter, productItemRequest: Partial<ProductItemRequest> | undefined | null = {}) : void {
    if (productItemRequest) {
        writer.writeGuidValue("productId", productItemRequest.productId);
        writer.writeStringValue("productName", productItemRequest.productName);
        writer.writeNumberValue("quantity", productItemRequest.quantity);
        writer.writeNumberValue("unitPrice", productItemRequest.unitPrice);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProductViewModel(writer: SerializationWriter, productViewModel: Partial<ProductViewModel> | undefined | null = {}) : void {
    if (productViewModel) {
        writer.writeStringValue("category", productViewModel.category);
        writer.writeStringValue("currencySymbol", productViewModel.currencySymbol);
        writer.writeStringValue("description", productViewModel.description);
        writer.writeStringValue("imageUrl", productViewModel.imageUrl);
        writer.writeStringValue("name", productViewModel.name);
        writer.writeNumberValue("price", productViewModel.price);
        writer.writeGuidValue("productId", productViewModel.productId);
        writer.writeNumberValue("quantityAddedToCart", productViewModel.quantityAddedToCart);
        writer.writeNumberValue("quantityInStock", productViewModel.quantityInStock);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProductViewModelIListApiResponse(writer: SerializationWriter, productViewModelIListApiResponse: Partial<ProductViewModelIListApiResponse> | undefined | null = {}) : void {
    if (productViewModelIListApiResponse) {
        writer.writeCollectionOfObjectValues<ProductViewModel>("data", productViewModelIListApiResponse.data, serializeProductViewModel);
        writer.writeStringValue("message", productViewModelIListApiResponse.message);
        writer.writeBooleanValue("success", productViewModelIListApiResponse.success);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQuoteItemViewModel(writer: SerializationWriter, quoteItemViewModel: Partial<QuoteItemViewModel> | undefined | null = {}) : void {
    if (quoteItemViewModel) {
        writer.writeStringValue("currencySymbol", quoteItemViewModel.currencySymbol);
        writer.writeGuidValue("productId", quoteItemViewModel.productId);
        writer.writeStringValue("productName", quoteItemViewModel.productName);
        writer.writeNumberValue("quantity", quoteItemViewModel.quantity);
        writer.writeNumberValue("unitPrice", quoteItemViewModel.unitPrice);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQuoteViewModel(writer: SerializationWriter, quoteViewModel: Partial<QuoteViewModel> | undefined | null = {}) : void {
    if (quoteViewModel) {
        writer.writeDateValue("createdAt", quoteViewModel.createdAt);
        writer.writeStringValue("currencyCode", quoteViewModel.currencyCode);
        writer.writeStringValue("currencySymbol", quoteViewModel.currencySymbol);
        writer.writeGuidValue("customerId", quoteViewModel.customerId);
        writer.writeCollectionOfObjectValues<QuoteItemViewModel>("items", quoteViewModel.items, serializeQuoteItemViewModel);
        writer.writeGuidValue("quoteId", quoteViewModel.quoteId);
        writer.writeStringValue("quoteStatus", quoteViewModel.quoteStatus);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQuoteViewModelApiResponse(writer: SerializationWriter, quoteViewModelApiResponse: Partial<QuoteViewModelApiResponse> | undefined | null = {}) : void {
    if (quoteViewModelApiResponse) {
        writer.writeObjectValue<QuoteViewModel>("data", quoteViewModelApiResponse.data, serializeQuoteViewModel);
        writer.writeStringValue("message", quoteViewModelApiResponse.message);
        writer.writeBooleanValue("success", quoteViewModelApiResponse.success);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRegisterCustomerRequest(writer: SerializationWriter, registerCustomerRequest: Partial<RegisterCustomerRequest> | undefined | null = {}) : void {
    if (registerCustomerRequest) {
        writer.writeNumberValue("creditLimit", registerCustomerRequest.creditLimit);
        writer.writeStringValue("email", registerCustomerRequest.email);
        writer.writeStringValue("name", registerCustomerRequest.name);
        writer.writeStringValue("password", registerCustomerRequest.password);
        writer.writeStringValue("passwordConfirm", registerCustomerRequest.passwordConfirm);
        writer.writeStringValue("shippingAddress", registerCustomerRequest.shippingAddress);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRegisterUserRequest(writer: SerializationWriter, registerUserRequest: Partial<RegisterUserRequest> | undefined | null = {}) : void {
    if (registerUserRequest) {
        writer.writeGuidValue("customerId", registerUserRequest.customerId);
        writer.writeStringValue("email", registerUserRequest.email);
        writer.writeStringValue("password", registerUserRequest.password);
        writer.writeStringValue("passwordConfirm", registerUserRequest.passwordConfirm);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeShipOrderRequest(writer: SerializationWriter, shipOrderRequest: Partial<ShipOrderRequest> | undefined | null = {}) : void {
    if (shipOrderRequest) {
        writer.writeGuidValue("orderId", shipOrderRequest.orderId);
        writer.writeCollectionOfObjectValues<ProductItemRequest>("productItems", shipOrderRequest.productItems, serializeProductItemRequest);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateCustomerRequest(writer: SerializationWriter, updateCustomerRequest: Partial<UpdateCustomerRequest> | undefined | null = {}) : void {
    if (updateCustomerRequest) {
        writer.writeNumberValue("creditLimit", updateCustomerRequest.creditLimit);
        writer.writeStringValue("name", updateCustomerRequest.name);
        writer.writeStringValue("shippingAddress", updateCustomerRequest.shippingAddress);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateOrderStatusRequest(writer: SerializationWriter, updateOrderStatusRequest: Partial<UpdateOrderStatusRequest> | undefined | null = {}) : void {
    if (updateOrderStatusRequest) {
        writer.writeGuidValue("customerId", updateOrderStatusRequest.customerId);
        writer.writeGuidValue("orderId", updateOrderStatusRequest.orderId);
        writer.writeNumberValue("orderStatusCode", updateOrderStatusRequest.orderStatusCode);
        writer.writeStringValue("orderStatusText", updateOrderStatusRequest.orderStatusText);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUserRegisteredResult(writer: SerializationWriter, userRegisteredResult: Partial<UserRegisteredResult> | undefined | null = {}) : void {
    if (userRegisteredResult) {
        writer.writeBooleanValue("succeeded", userRegisteredResult.succeeded);
        writer.writeStringValue("userId", userRegisteredResult.userId);
    }
}
export interface ShipOrderRequest extends Parsable {
    /**
     * The orderId property
     */
    orderId?: Guid | null;
    /**
     * The productItems property
     */
    productItems?: ProductItemRequest[] | null;
}
export interface UpdateCustomerRequest extends Parsable {
    /**
     * The creditLimit property
     */
    creditLimit?: number | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The shippingAddress property
     */
    shippingAddress?: string | null;
}
export interface UpdateOrderStatusRequest extends Parsable {
    /**
     * The customerId property
     */
    customerId?: Guid | null;
    /**
     * The orderId property
     */
    orderId?: Guid | null;
    /**
     * The orderStatusCode property
     */
    orderStatusCode?: number | null;
    /**
     * The orderStatusText property
     */
    orderStatusText?: string | null;
}
export interface UserRegisteredResult extends Parsable {
    /**
     * The succeeded property
     */
    succeeded?: boolean | null;
    /**
     * The userId property
     */
    userId?: string | null;
}
/* tslint:enable */
/* eslint-enable */
