/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AddQuoteItemRequest extends Parsable {
    /**
     * The productId property
     */
    productId?: Guid | null;
    /**
     * The quantity property
     */
    quantity?: number | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AddQuoteItemRequest}
 */
// @ts-ignore
export function createAddQuoteItemRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAddQuoteItemRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CustomerDetailsApiResponse}
 */
// @ts-ignore
export function createCustomerDetailsApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCustomerDetailsApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CustomerDetails}
 */
// @ts-ignore
export function createCustomerDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCustomerDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CustomerEventHistory}
 */
// @ts-ignore
export function createCustomerEventHistoryFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCustomerEventHistory;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CustomerEventHistoryIReadOnlyListApiResponse}
 */
// @ts-ignore
export function createCustomerEventHistoryIReadOnlyListApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCustomerEventHistoryIReadOnlyListApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CustomerManagementProblemDetails}
 */
// @ts-ignore
export function createCustomerManagementProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCustomerManagementProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GetProductsRequest}
 */
// @ts-ignore
export function createGetProductsRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetProductsRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InventoryManagementProblemDetails}
 */
// @ts-ignore
export function createInventoryManagementProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInventoryManagementProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InventoryStockUnitEventHistory}
 */
// @ts-ignore
export function createInventoryStockUnitEventHistoryFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInventoryStockUnitEventHistory;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InventoryStockUnitEventHistoryIReadOnlyListApiResponse}
 */
// @ts-ignore
export function createInventoryStockUnitEventHistoryIReadOnlyListApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInventoryStockUnitEventHistoryIReadOnlyListApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginRequest}
 */
// @ts-ignore
export function createLoginRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginResult}
 */
// @ts-ignore
export function createLoginResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OpenQuoteRequest}
 */
// @ts-ignore
export function createOpenQuoteRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOpenQuoteRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OrderEventHistory}
 */
// @ts-ignore
export function createOrderEventHistoryFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOrderEventHistory;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OrderEventHistoryIReadOnlyListApiResponse}
 */
// @ts-ignore
export function createOrderEventHistoryIReadOnlyListApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOrderEventHistoryIReadOnlyListApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OrderLineViewModel}
 */
// @ts-ignore
export function createOrderLineViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOrderLineViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OrderViewModel}
 */
// @ts-ignore
export function createOrderViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOrderViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OrderViewModelIReadOnlyListApiResponse}
 */
// @ts-ignore
export function createOrderViewModelIReadOnlyListApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOrderViewModelIReadOnlyListApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProblemDetails}
 */
// @ts-ignore
export function createProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProductCatalogProblemDetails}
 */
// @ts-ignore
export function createProductCatalogProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProductCatalogProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProductViewModel}
 */
// @ts-ignore
export function createProductViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProductViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProductViewModelIListApiResponse}
 */
// @ts-ignore
export function createProductViewModelIListApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProductViewModelIListApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QuoteEventHistory}
 */
// @ts-ignore
export function createQuoteEventHistoryFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQuoteEventHistory;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QuoteEventHistoryIReadOnlyListApiResponse}
 */
// @ts-ignore
export function createQuoteEventHistoryIReadOnlyListApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQuoteEventHistoryIReadOnlyListApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QuoteItemViewModel}
 */
// @ts-ignore
export function createQuoteItemViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQuoteItemViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QuoteManagementProblemDetails}
 */
// @ts-ignore
export function createQuoteManagementProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQuoteManagementProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QuoteViewModelApiResponse}
 */
// @ts-ignore
export function createQuoteViewModelApiResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQuoteViewModelApiResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QuoteViewModel}
 */
// @ts-ignore
export function createQuoteViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQuoteViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RegisterCustomerRequest}
 */
// @ts-ignore
export function createRegisterCustomerRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRegisterCustomerRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateCustomerRequest}
 */
// @ts-ignore
export function createUpdateCustomerRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateCustomerRequest;
}
export interface CustomerDetails extends Parsable {
    /**
     * The creditLimit property
     */
    creditLimit?: number | null;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The shippingAddress property
     */
    shippingAddress?: string | null;
}
export interface CustomerDetailsApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: CustomerDetails | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface CustomerEventHistory extends Parsable {
    /**
     * The aggregateId property
     */
    aggregateId?: Guid | null;
    /**
     * The eventData property
     */
    eventData?: string | null;
    /**
     * The eventTypeName property
     */
    eventTypeName?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The timestamp property
     */
    timestamp?: Date | null;
}
export interface CustomerEventHistoryIReadOnlyListApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: CustomerEventHistory[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface CustomerManagementProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
    /**
     * The additionalData property
     */
    additionalData?: Record<string, unknown>;
}
/**
 * The deserialization information for the current model
 * @param AddQuoteItemRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAddQuoteItemRequest(addQuoteItemRequest: Partial<AddQuoteItemRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "productId": n => { addQuoteItemRequest.productId = n.getGuidValue(); },
        "quantity": n => { addQuoteItemRequest.quantity = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CustomerDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCustomerDetails(customerDetails: Partial<CustomerDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "creditLimit": n => { customerDetails.creditLimit = n.getNumberValue(); },
        "email": n => { customerDetails.email = n.getStringValue(); },
        "id": n => { customerDetails.id = n.getGuidValue(); },
        "name": n => { customerDetails.name = n.getStringValue(); },
        "shippingAddress": n => { customerDetails.shippingAddress = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CustomerDetailsApiResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCustomerDetailsApiResponse(customerDetailsApiResponse: Partial<CustomerDetailsApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { customerDetailsApiResponse.data = n.getObjectValue<CustomerDetails>(createCustomerDetailsFromDiscriminatorValue); },
        "message": n => { customerDetailsApiResponse.message = n.getStringValue(); },
        "success": n => { customerDetailsApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CustomerEventHistory The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCustomerEventHistory(customerEventHistory: Partial<CustomerEventHistory> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "aggregateId": n => { customerEventHistory.aggregateId = n.getGuidValue(); },
        "eventData": n => { customerEventHistory.eventData = n.getStringValue(); },
        "eventTypeName": n => { customerEventHistory.eventTypeName = n.getStringValue(); },
        "id": n => { customerEventHistory.id = n.getGuidValue(); },
        "timestamp": n => { customerEventHistory.timestamp = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CustomerEventHistoryIReadOnlyListApiResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCustomerEventHistoryIReadOnlyListApiResponse(customerEventHistoryIReadOnlyListApiResponse: Partial<CustomerEventHistoryIReadOnlyListApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { customerEventHistoryIReadOnlyListApiResponse.data = n.getCollectionOfObjectValues<CustomerEventHistory>(createCustomerEventHistoryFromDiscriminatorValue); },
        "message": n => { customerEventHistoryIReadOnlyListApiResponse.message = n.getStringValue(); },
        "success": n => { customerEventHistoryIReadOnlyListApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CustomerManagementProblemDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCustomerManagementProblemDetails(customerManagementProblemDetails: Partial<CustomerManagementProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { customerManagementProblemDetails.detail = n.getStringValue(); },
        "instance": n => { customerManagementProblemDetails.instance = n.getStringValue(); },
        "status": n => { customerManagementProblemDetails.status = n.getNumberValue(); },
        "title": n => { customerManagementProblemDetails.title = n.getStringValue(); },
        "type": n => { customerManagementProblemDetails.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param GetProductsRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGetProductsRequest(getProductsRequest: Partial<GetProductsRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "currencyCode": n => { getProductsRequest.currencyCode = n.getStringValue(); },
        "productIds": n => { getProductsRequest.productIds = n.getCollectionOfPrimitiveValues<Guid>(); },
    }
}
/**
 * The deserialization information for the current model
 * @param InventoryManagementProblemDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInventoryManagementProblemDetails(inventoryManagementProblemDetails: Partial<InventoryManagementProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { inventoryManagementProblemDetails.detail = n.getStringValue(); },
        "instance": n => { inventoryManagementProblemDetails.instance = n.getStringValue(); },
        "status": n => { inventoryManagementProblemDetails.status = n.getNumberValue(); },
        "title": n => { inventoryManagementProblemDetails.title = n.getStringValue(); },
        "type": n => { inventoryManagementProblemDetails.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param InventoryStockUnitEventHistory The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInventoryStockUnitEventHistory(inventoryStockUnitEventHistory: Partial<InventoryStockUnitEventHistory> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "aggregateId": n => { inventoryStockUnitEventHistory.aggregateId = n.getGuidValue(); },
        "eventData": n => { inventoryStockUnitEventHistory.eventData = n.getStringValue(); },
        "eventTypeName": n => { inventoryStockUnitEventHistory.eventTypeName = n.getStringValue(); },
        "id": n => { inventoryStockUnitEventHistory.id = n.getGuidValue(); },
        "timestamp": n => { inventoryStockUnitEventHistory.timestamp = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param InventoryStockUnitEventHistoryIReadOnlyListApiResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInventoryStockUnitEventHistoryIReadOnlyListApiResponse(inventoryStockUnitEventHistoryIReadOnlyListApiResponse: Partial<InventoryStockUnitEventHistoryIReadOnlyListApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { inventoryStockUnitEventHistoryIReadOnlyListApiResponse.data = n.getCollectionOfObjectValues<InventoryStockUnitEventHistory>(createInventoryStockUnitEventHistoryFromDiscriminatorValue); },
        "message": n => { inventoryStockUnitEventHistoryIReadOnlyListApiResponse.message = n.getStringValue(); },
        "success": n => { inventoryStockUnitEventHistoryIReadOnlyListApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginRequest(loginRequest: Partial<LoginRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { loginRequest.email = n.getStringValue(); },
        "password": n => { loginRequest.password = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginResult(loginResult: Partial<LoginResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "accessToken": n => { loginResult.accessToken = n.getStringValue(); },
        "errorDescription": n => { loginResult.errorDescription = n.getStringValue(); },
        "identityToken": n => { loginResult.identityToken = n.getStringValue(); },
        "refreshToken": n => { loginResult.refreshToken = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param OpenQuoteRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOpenQuoteRequest(openQuoteRequest: Partial<OpenQuoteRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "currencyCode": n => { openQuoteRequest.currencyCode = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param OrderEventHistory The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOrderEventHistory(orderEventHistory: Partial<OrderEventHistory> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "aggregateId": n => { orderEventHistory.aggregateId = n.getGuidValue(); },
        "eventData": n => { orderEventHistory.eventData = n.getStringValue(); },
        "eventTypeName": n => { orderEventHistory.eventTypeName = n.getStringValue(); },
        "id": n => { orderEventHistory.id = n.getGuidValue(); },
        "timestamp": n => { orderEventHistory.timestamp = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param OrderEventHistoryIReadOnlyListApiResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOrderEventHistoryIReadOnlyListApiResponse(orderEventHistoryIReadOnlyListApiResponse: Partial<OrderEventHistoryIReadOnlyListApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { orderEventHistoryIReadOnlyListApiResponse.data = n.getCollectionOfObjectValues<OrderEventHistory>(createOrderEventHistoryFromDiscriminatorValue); },
        "message": n => { orderEventHistoryIReadOnlyListApiResponse.message = n.getStringValue(); },
        "success": n => { orderEventHistoryIReadOnlyListApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param OrderLineViewModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOrderLineViewModel(orderLineViewModel: Partial<OrderLineViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "productId": n => { orderLineViewModel.productId = n.getGuidValue(); },
        "productName": n => { orderLineViewModel.productName = n.getStringValue(); },
        "quantity": n => { orderLineViewModel.quantity = n.getNumberValue(); },
        "unitPrice": n => { orderLineViewModel.unitPrice = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param OrderViewModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOrderViewModel(orderViewModel: Partial<OrderViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { orderViewModel.createdAt = n.getDateValue(); },
        "currencySymbol": n => { orderViewModel.currencySymbol = n.getStringValue(); },
        "customerId": n => { orderViewModel.customerId = n.getGuidValue(); },
        "orderId": n => { orderViewModel.orderId = n.getGuidValue(); },
        "orderLines": n => { orderViewModel.orderLines = n.getCollectionOfObjectValues<OrderLineViewModel>(createOrderLineViewModelFromDiscriminatorValue); },
        "quoteId": n => { orderViewModel.quoteId = n.getGuidValue(); },
        "statusCode": n => { orderViewModel.statusCode = n.getNumberValue(); },
        "statusText": n => { orderViewModel.statusText = n.getStringValue(); },
        "totalPrice": n => { orderViewModel.totalPrice = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param OrderViewModelIReadOnlyListApiResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOrderViewModelIReadOnlyListApiResponse(orderViewModelIReadOnlyListApiResponse: Partial<OrderViewModelIReadOnlyListApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { orderViewModelIReadOnlyListApiResponse.data = n.getCollectionOfObjectValues<OrderViewModel>(createOrderViewModelFromDiscriminatorValue); },
        "message": n => { orderViewModelIReadOnlyListApiResponse.message = n.getStringValue(); },
        "success": n => { orderViewModelIReadOnlyListApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProblemDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProblemDetails(problemDetails: Partial<ProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { problemDetails.detail = n.getStringValue(); },
        "instance": n => { problemDetails.instance = n.getStringValue(); },
        "status": n => { problemDetails.status = n.getNumberValue(); },
        "title": n => { problemDetails.title = n.getStringValue(); },
        "type": n => { problemDetails.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProductCatalogProblemDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProductCatalogProblemDetails(productCatalogProblemDetails: Partial<ProductCatalogProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { productCatalogProblemDetails.detail = n.getStringValue(); },
        "instance": n => { productCatalogProblemDetails.instance = n.getStringValue(); },
        "status": n => { productCatalogProblemDetails.status = n.getNumberValue(); },
        "title": n => { productCatalogProblemDetails.title = n.getStringValue(); },
        "type": n => { productCatalogProblemDetails.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProductViewModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProductViewModel(productViewModel: Partial<ProductViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "category": n => { productViewModel.category = n.getStringValue(); },
        "currencySymbol": n => { productViewModel.currencySymbol = n.getStringValue(); },
        "description": n => { productViewModel.description = n.getStringValue(); },
        "imageUrl": n => { productViewModel.imageUrl = n.getStringValue(); },
        "name": n => { productViewModel.name = n.getStringValue(); },
        "price": n => { productViewModel.price = n.getNumberValue(); },
        "productId": n => { productViewModel.productId = n.getGuidValue(); },
        "quantityAddedToCart": n => { productViewModel.quantityAddedToCart = n.getNumberValue(); },
        "quantityInStock": n => { productViewModel.quantityInStock = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProductViewModelIListApiResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProductViewModelIListApiResponse(productViewModelIListApiResponse: Partial<ProductViewModelIListApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { productViewModelIListApiResponse.data = n.getCollectionOfObjectValues<ProductViewModel>(createProductViewModelFromDiscriminatorValue); },
        "message": n => { productViewModelIListApiResponse.message = n.getStringValue(); },
        "success": n => { productViewModelIListApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param QuoteEventHistory The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQuoteEventHistory(quoteEventHistory: Partial<QuoteEventHistory> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "aggregateId": n => { quoteEventHistory.aggregateId = n.getGuidValue(); },
        "eventData": n => { quoteEventHistory.eventData = n.getStringValue(); },
        "eventTypeName": n => { quoteEventHistory.eventTypeName = n.getStringValue(); },
        "id": n => { quoteEventHistory.id = n.getGuidValue(); },
        "timestamp": n => { quoteEventHistory.timestamp = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param QuoteEventHistoryIReadOnlyListApiResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQuoteEventHistoryIReadOnlyListApiResponse(quoteEventHistoryIReadOnlyListApiResponse: Partial<QuoteEventHistoryIReadOnlyListApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { quoteEventHistoryIReadOnlyListApiResponse.data = n.getCollectionOfObjectValues<QuoteEventHistory>(createQuoteEventHistoryFromDiscriminatorValue); },
        "message": n => { quoteEventHistoryIReadOnlyListApiResponse.message = n.getStringValue(); },
        "success": n => { quoteEventHistoryIReadOnlyListApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param QuoteItemViewModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQuoteItemViewModel(quoteItemViewModel: Partial<QuoteItemViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "currencySymbol": n => { quoteItemViewModel.currencySymbol = n.getStringValue(); },
        "productId": n => { quoteItemViewModel.productId = n.getGuidValue(); },
        "productName": n => { quoteItemViewModel.productName = n.getStringValue(); },
        "quantity": n => { quoteItemViewModel.quantity = n.getNumberValue(); },
        "unitPrice": n => { quoteItemViewModel.unitPrice = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param QuoteManagementProblemDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQuoteManagementProblemDetails(quoteManagementProblemDetails: Partial<QuoteManagementProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { quoteManagementProblemDetails.detail = n.getStringValue(); },
        "instance": n => { quoteManagementProblemDetails.instance = n.getStringValue(); },
        "status": n => { quoteManagementProblemDetails.status = n.getNumberValue(); },
        "title": n => { quoteManagementProblemDetails.title = n.getStringValue(); },
        "type": n => { quoteManagementProblemDetails.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param QuoteViewModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQuoteViewModel(quoteViewModel: Partial<QuoteViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { quoteViewModel.createdAt = n.getDateValue(); },
        "currencyCode": n => { quoteViewModel.currencyCode = n.getStringValue(); },
        "currencySymbol": n => { quoteViewModel.currencySymbol = n.getStringValue(); },
        "customerId": n => { quoteViewModel.customerId = n.getGuidValue(); },
        "items": n => { quoteViewModel.items = n.getCollectionOfObjectValues<QuoteItemViewModel>(createQuoteItemViewModelFromDiscriminatorValue); },
        "quoteId": n => { quoteViewModel.quoteId = n.getGuidValue(); },
        "quoteStatus": n => { quoteViewModel.quoteStatus = n.getStringValue(); },
        "totalPrice": n => { quoteViewModel.totalPrice = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param QuoteViewModelApiResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQuoteViewModelApiResponse(quoteViewModelApiResponse: Partial<QuoteViewModelApiResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { quoteViewModelApiResponse.data = n.getObjectValue<QuoteViewModel>(createQuoteViewModelFromDiscriminatorValue); },
        "message": n => { quoteViewModelApiResponse.message = n.getStringValue(); },
        "success": n => { quoteViewModelApiResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RegisterCustomerRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRegisterCustomerRequest(registerCustomerRequest: Partial<RegisterCustomerRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "creditLimit": n => { registerCustomerRequest.creditLimit = n.getNumberValue(); },
        "email": n => { registerCustomerRequest.email = n.getStringValue(); },
        "name": n => { registerCustomerRequest.name = n.getStringValue(); },
        "password": n => { registerCustomerRequest.password = n.getStringValue(); },
        "passwordConfirm": n => { registerCustomerRequest.passwordConfirm = n.getStringValue(); },
        "shippingAddress": n => { registerCustomerRequest.shippingAddress = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateCustomerRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateCustomerRequest(updateCustomerRequest: Partial<UpdateCustomerRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "creditLimit": n => { updateCustomerRequest.creditLimit = n.getNumberValue(); },
        "name": n => { updateCustomerRequest.name = n.getStringValue(); },
        "shippingAddress": n => { updateCustomerRequest.shippingAddress = n.getStringValue(); },
    }
}
export interface GetProductsRequest extends Parsable {
    /**
     * The currencyCode property
     */
    currencyCode?: string | null;
    /**
     * The productIds property
     */
    productIds?: Guid[] | null;
}
export interface InventoryManagementProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
    /**
     * The additionalData property
     */
    additionalData?: Record<string, unknown>;
}
export interface InventoryStockUnitEventHistory extends Parsable {
    /**
     * The aggregateId property
     */
    aggregateId?: Guid | null;
    /**
     * The eventData property
     */
    eventData?: string | null;
    /**
     * The eventTypeName property
     */
    eventTypeName?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The timestamp property
     */
    timestamp?: Date | null;
}
export interface InventoryStockUnitEventHistoryIReadOnlyListApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: InventoryStockUnitEventHistory[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface LoginRequest extends Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
}
export interface LoginResult extends Parsable {
    /**
     * The accessToken property
     */
    accessToken?: string | null;
    /**
     * The errorDescription property
     */
    errorDescription?: string | null;
    /**
     * The identityToken property
     */
    identityToken?: string | null;
    /**
     * The refreshToken property
     */
    refreshToken?: string | null;
}
export interface OpenQuoteRequest extends Parsable {
    /**
     * The currencyCode property
     */
    currencyCode?: string | null;
}
export interface OrderEventHistory extends Parsable {
    /**
     * The aggregateId property
     */
    aggregateId?: Guid | null;
    /**
     * The eventData property
     */
    eventData?: string | null;
    /**
     * The eventTypeName property
     */
    eventTypeName?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The timestamp property
     */
    timestamp?: Date | null;
}
export interface OrderEventHistoryIReadOnlyListApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: OrderEventHistory[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface OrderLineViewModel extends Parsable {
    /**
     * The productId property
     */
    productId?: Guid | null;
    /**
     * The productName property
     */
    productName?: string | null;
    /**
     * The quantity property
     */
    quantity?: number | null;
    /**
     * The unitPrice property
     */
    unitPrice?: number | null;
}
export interface OrderViewModel extends Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The currencySymbol property
     */
    currencySymbol?: string | null;
    /**
     * The customerId property
     */
    customerId?: Guid | null;
    /**
     * The orderId property
     */
    orderId?: Guid | null;
    /**
     * The orderLines property
     */
    orderLines?: OrderLineViewModel[] | null;
    /**
     * The quoteId property
     */
    quoteId?: Guid | null;
    /**
     * The statusCode property
     */
    statusCode?: number | null;
    /**
     * The statusText property
     */
    statusText?: string | null;
    /**
     * The totalPrice property
     */
    totalPrice?: number | null;
}
export interface OrderViewModelIReadOnlyListApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: OrderViewModel[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface ProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
    /**
     * The additionalData property
     */
    additionalData?: Record<string, unknown>;
}
export interface ProductCatalogProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
    /**
     * The additionalData property
     */
    additionalData?: Record<string, unknown>;
}
export interface ProductViewModel extends Parsable {
    /**
     * The category property
     */
    category?: string | null;
    /**
     * The currencySymbol property
     */
    currencySymbol?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The imageUrl property
     */
    imageUrl?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The price property
     */
    price?: number | null;
    /**
     * The productId property
     */
    productId?: Guid | null;
    /**
     * The quantityAddedToCart property
     */
    quantityAddedToCart?: number | null;
    /**
     * The quantityInStock property
     */
    quantityInStock?: number | null;
}
export interface ProductViewModelIListApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: ProductViewModel[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface QuoteEventHistory extends Parsable {
    /**
     * The aggregateId property
     */
    aggregateId?: Guid | null;
    /**
     * The eventData property
     */
    eventData?: string | null;
    /**
     * The eventTypeName property
     */
    eventTypeName?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The timestamp property
     */
    timestamp?: Date | null;
}
export interface QuoteEventHistoryIReadOnlyListApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: QuoteEventHistory[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface QuoteItemViewModel extends Parsable {
    /**
     * The currencySymbol property
     */
    currencySymbol?: string | null;
    /**
     * The productId property
     */
    productId?: Guid | null;
    /**
     * The productName property
     */
    productName?: string | null;
    /**
     * The quantity property
     */
    quantity?: number | null;
    /**
     * The unitPrice property
     */
    unitPrice?: number | null;
}
export interface QuoteManagementProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
    /**
     * The additionalData property
     */
    additionalData?: Record<string, unknown>;
}
export interface QuoteViewModel extends Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The currencyCode property
     */
    currencyCode?: string | null;
    /**
     * The currencySymbol property
     */
    currencySymbol?: string | null;
    /**
     * The customerId property
     */
    customerId?: Guid | null;
    /**
     * The items property
     */
    items?: QuoteItemViewModel[] | null;
    /**
     * The quoteId property
     */
    quoteId?: Guid | null;
    /**
     * The quoteStatus property
     */
    quoteStatus?: string | null;
    /**
     * The totalPrice property
     */
    totalPrice?: number | null;
}
export interface QuoteViewModelApiResponse extends Parsable {
    /**
     * The data property
     */
    data?: QuoteViewModel | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface RegisterCustomerRequest extends Parsable {
    /**
     * The creditLimit property
     */
    creditLimit?: number | null;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The password property
     */
    password?: string | null;
    /**
     * The passwordConfirm property
     */
    passwordConfirm?: string | null;
    /**
     * The shippingAddress property
     */
    shippingAddress?: string | null;
}
/**
 * Serializes information the current object
 * @param AddQuoteItemRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAddQuoteItemRequest(writer: SerializationWriter, addQuoteItemRequest: Partial<AddQuoteItemRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!addQuoteItemRequest || isSerializingDerivedType) { return; }
    writer.writeGuidValue("productId", addQuoteItemRequest.productId);
    writer.writeNumberValue("quantity", addQuoteItemRequest.quantity);
}
/**
 * Serializes information the current object
 * @param CustomerDetails The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCustomerDetails(writer: SerializationWriter, customerDetails: Partial<CustomerDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!customerDetails || isSerializingDerivedType) { return; }
    writer.writeNumberValue("creditLimit", customerDetails.creditLimit);
    writer.writeStringValue("email", customerDetails.email);
    writer.writeGuidValue("id", customerDetails.id);
    writer.writeStringValue("name", customerDetails.name);
    writer.writeStringValue("shippingAddress", customerDetails.shippingAddress);
}
/**
 * Serializes information the current object
 * @param CustomerDetailsApiResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCustomerDetailsApiResponse(writer: SerializationWriter, customerDetailsApiResponse: Partial<CustomerDetailsApiResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!customerDetailsApiResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<CustomerDetails>("data", customerDetailsApiResponse.data, serializeCustomerDetails);
    writer.writeStringValue("message", customerDetailsApiResponse.message);
    writer.writeBooleanValue("success", customerDetailsApiResponse.success);
}
/**
 * Serializes information the current object
 * @param CustomerEventHistory The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCustomerEventHistory(writer: SerializationWriter, customerEventHistory: Partial<CustomerEventHistory> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!customerEventHistory || isSerializingDerivedType) { return; }
    writer.writeGuidValue("aggregateId", customerEventHistory.aggregateId);
    writer.writeStringValue("eventData", customerEventHistory.eventData);
    writer.writeStringValue("eventTypeName", customerEventHistory.eventTypeName);
    writer.writeGuidValue("id", customerEventHistory.id);
    writer.writeDateValue("timestamp", customerEventHistory.timestamp);
}
/**
 * Serializes information the current object
 * @param CustomerEventHistoryIReadOnlyListApiResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCustomerEventHistoryIReadOnlyListApiResponse(writer: SerializationWriter, customerEventHistoryIReadOnlyListApiResponse: Partial<CustomerEventHistoryIReadOnlyListApiResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!customerEventHistoryIReadOnlyListApiResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<CustomerEventHistory>("data", customerEventHistoryIReadOnlyListApiResponse.data, serializeCustomerEventHistory);
    writer.writeStringValue("message", customerEventHistoryIReadOnlyListApiResponse.message);
    writer.writeBooleanValue("success", customerEventHistoryIReadOnlyListApiResponse.success);
}
/**
 * Serializes information the current object
 * @param CustomerManagementProblemDetails The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCustomerManagementProblemDetails(writer: SerializationWriter, customerManagementProblemDetails: Partial<CustomerManagementProblemDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!customerManagementProblemDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", customerManagementProblemDetails.detail);
    writer.writeStringValue("instance", customerManagementProblemDetails.instance);
    writer.writeNumberValue("status", customerManagementProblemDetails.status);
    writer.writeStringValue("title", customerManagementProblemDetails.title);
    writer.writeStringValue("type", customerManagementProblemDetails.type);
    writer.writeAdditionalData(customerManagementProblemDetails.additionalData);
}
/**
 * Serializes information the current object
 * @param GetProductsRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGetProductsRequest(writer: SerializationWriter, getProductsRequest: Partial<GetProductsRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!getProductsRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("currencyCode", getProductsRequest.currencyCode);
    writer.writeCollectionOfPrimitiveValues<Guid>("productIds", getProductsRequest.productIds);
}
/**
 * Serializes information the current object
 * @param InventoryManagementProblemDetails The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInventoryManagementProblemDetails(writer: SerializationWriter, inventoryManagementProblemDetails: Partial<InventoryManagementProblemDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!inventoryManagementProblemDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", inventoryManagementProblemDetails.detail);
    writer.writeStringValue("instance", inventoryManagementProblemDetails.instance);
    writer.writeNumberValue("status", inventoryManagementProblemDetails.status);
    writer.writeStringValue("title", inventoryManagementProblemDetails.title);
    writer.writeStringValue("type", inventoryManagementProblemDetails.type);
    writer.writeAdditionalData(inventoryManagementProblemDetails.additionalData);
}
/**
 * Serializes information the current object
 * @param InventoryStockUnitEventHistory The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInventoryStockUnitEventHistory(writer: SerializationWriter, inventoryStockUnitEventHistory: Partial<InventoryStockUnitEventHistory> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!inventoryStockUnitEventHistory || isSerializingDerivedType) { return; }
    writer.writeGuidValue("aggregateId", inventoryStockUnitEventHistory.aggregateId);
    writer.writeStringValue("eventData", inventoryStockUnitEventHistory.eventData);
    writer.writeStringValue("eventTypeName", inventoryStockUnitEventHistory.eventTypeName);
    writer.writeGuidValue("id", inventoryStockUnitEventHistory.id);
    writer.writeDateValue("timestamp", inventoryStockUnitEventHistory.timestamp);
}
/**
 * Serializes information the current object
 * @param InventoryStockUnitEventHistoryIReadOnlyListApiResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInventoryStockUnitEventHistoryIReadOnlyListApiResponse(writer: SerializationWriter, inventoryStockUnitEventHistoryIReadOnlyListApiResponse: Partial<InventoryStockUnitEventHistoryIReadOnlyListApiResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!inventoryStockUnitEventHistoryIReadOnlyListApiResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<InventoryStockUnitEventHistory>("data", inventoryStockUnitEventHistoryIReadOnlyListApiResponse.data, serializeInventoryStockUnitEventHistory);
    writer.writeStringValue("message", inventoryStockUnitEventHistoryIReadOnlyListApiResponse.message);
    writer.writeBooleanValue("success", inventoryStockUnitEventHistoryIReadOnlyListApiResponse.success);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginRequest(writer: SerializationWriter, loginRequest: Partial<LoginRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", loginRequest.email);
    writer.writeStringValue("password", loginRequest.password);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginResult The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginResult(writer: SerializationWriter, loginResult: Partial<LoginResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginResult || isSerializingDerivedType) { return; }
    writer.writeStringValue("accessToken", loginResult.accessToken);
    writer.writeStringValue("errorDescription", loginResult.errorDescription);
    writer.writeStringValue("identityToken", loginResult.identityToken);
    writer.writeStringValue("refreshToken", loginResult.refreshToken);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param OpenQuoteRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOpenQuoteRequest(writer: SerializationWriter, openQuoteRequest: Partial<OpenQuoteRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!openQuoteRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("currencyCode", openQuoteRequest.currencyCode);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param OrderEventHistory The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOrderEventHistory(writer: SerializationWriter, orderEventHistory: Partial<OrderEventHistory> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!orderEventHistory || isSerializingDerivedType) { return; }
    writer.writeGuidValue("aggregateId", orderEventHistory.aggregateId);
    writer.writeStringValue("eventData", orderEventHistory.eventData);
    writer.writeStringValue("eventTypeName", orderEventHistory.eventTypeName);
    writer.writeGuidValue("id", orderEventHistory.id);
    writer.writeDateValue("timestamp", orderEventHistory.timestamp);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param OrderEventHistoryIReadOnlyListApiResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOrderEventHistoryIReadOnlyListApiResponse(writer: SerializationWriter, orderEventHistoryIReadOnlyListApiResponse: Partial<OrderEventHistoryIReadOnlyListApiResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!orderEventHistoryIReadOnlyListApiResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<OrderEventHistory>("data", orderEventHistoryIReadOnlyListApiResponse.data, serializeOrderEventHistory);
    writer.writeStringValue("message", orderEventHistoryIReadOnlyListApiResponse.message);
    writer.writeBooleanValue("success", orderEventHistoryIReadOnlyListApiResponse.success);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param OrderLineViewModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOrderLineViewModel(writer: SerializationWriter, orderLineViewModel: Partial<OrderLineViewModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!orderLineViewModel || isSerializingDerivedType) { return; }
    writer.writeGuidValue("productId", orderLineViewModel.productId);
    writer.writeStringValue("productName", orderLineViewModel.productName);
    writer.writeNumberValue("quantity", orderLineViewModel.quantity);
    writer.writeNumberValue("unitPrice", orderLineViewModel.unitPrice);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param OrderViewModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOrderViewModel(writer: SerializationWriter, orderViewModel: Partial<OrderViewModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!orderViewModel || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", orderViewModel.createdAt);
    writer.writeStringValue("currencySymbol", orderViewModel.currencySymbol);
    writer.writeGuidValue("customerId", orderViewModel.customerId);
    writer.writeGuidValue("orderId", orderViewModel.orderId);
    writer.writeCollectionOfObjectValues<OrderLineViewModel>("orderLines", orderViewModel.orderLines, serializeOrderLineViewModel);
    writer.writeGuidValue("quoteId", orderViewModel.quoteId);
    writer.writeNumberValue("statusCode", orderViewModel.statusCode);
    writer.writeStringValue("statusText", orderViewModel.statusText);
    writer.writeNumberValue("totalPrice", orderViewModel.totalPrice);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param OrderViewModelIReadOnlyListApiResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOrderViewModelIReadOnlyListApiResponse(writer: SerializationWriter, orderViewModelIReadOnlyListApiResponse: Partial<OrderViewModelIReadOnlyListApiResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!orderViewModelIReadOnlyListApiResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<OrderViewModel>("data", orderViewModelIReadOnlyListApiResponse.data, serializeOrderViewModel);
    writer.writeStringValue("message", orderViewModelIReadOnlyListApiResponse.message);
    writer.writeBooleanValue("success", orderViewModelIReadOnlyListApiResponse.success);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProblemDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProblemDetails(writer: SerializationWriter, problemDetails: Partial<ProblemDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!problemDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", problemDetails.detail);
    writer.writeStringValue("instance", problemDetails.instance);
    writer.writeNumberValue("status", problemDetails.status);
    writer.writeStringValue("title", problemDetails.title);
    writer.writeStringValue("type", problemDetails.type);
    writer.writeAdditionalData(problemDetails.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProductCatalogProblemDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProductCatalogProblemDetails(writer: SerializationWriter, productCatalogProblemDetails: Partial<ProductCatalogProblemDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!productCatalogProblemDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", productCatalogProblemDetails.detail);
    writer.writeStringValue("instance", productCatalogProblemDetails.instance);
    writer.writeNumberValue("status", productCatalogProblemDetails.status);
    writer.writeStringValue("title", productCatalogProblemDetails.title);
    writer.writeStringValue("type", productCatalogProblemDetails.type);
    writer.writeAdditionalData(productCatalogProblemDetails.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProductViewModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProductViewModel(writer: SerializationWriter, productViewModel: Partial<ProductViewModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!productViewModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("category", productViewModel.category);
    writer.writeStringValue("currencySymbol", productViewModel.currencySymbol);
    writer.writeStringValue("description", productViewModel.description);
    writer.writeStringValue("imageUrl", productViewModel.imageUrl);
    writer.writeStringValue("name", productViewModel.name);
    writer.writeNumberValue("price", productViewModel.price);
    writer.writeGuidValue("productId", productViewModel.productId);
    writer.writeNumberValue("quantityAddedToCart", productViewModel.quantityAddedToCart);
    writer.writeNumberValue("quantityInStock", productViewModel.quantityInStock);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProductViewModelIListApiResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProductViewModelIListApiResponse(writer: SerializationWriter, productViewModelIListApiResponse: Partial<ProductViewModelIListApiResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!productViewModelIListApiResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ProductViewModel>("data", productViewModelIListApiResponse.data, serializeProductViewModel);
    writer.writeStringValue("message", productViewModelIListApiResponse.message);
    writer.writeBooleanValue("success", productViewModelIListApiResponse.success);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QuoteEventHistory The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQuoteEventHistory(writer: SerializationWriter, quoteEventHistory: Partial<QuoteEventHistory> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!quoteEventHistory || isSerializingDerivedType) { return; }
    writer.writeGuidValue("aggregateId", quoteEventHistory.aggregateId);
    writer.writeStringValue("eventData", quoteEventHistory.eventData);
    writer.writeStringValue("eventTypeName", quoteEventHistory.eventTypeName);
    writer.writeGuidValue("id", quoteEventHistory.id);
    writer.writeDateValue("timestamp", quoteEventHistory.timestamp);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QuoteEventHistoryIReadOnlyListApiResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQuoteEventHistoryIReadOnlyListApiResponse(writer: SerializationWriter, quoteEventHistoryIReadOnlyListApiResponse: Partial<QuoteEventHistoryIReadOnlyListApiResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!quoteEventHistoryIReadOnlyListApiResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<QuoteEventHistory>("data", quoteEventHistoryIReadOnlyListApiResponse.data, serializeQuoteEventHistory);
    writer.writeStringValue("message", quoteEventHistoryIReadOnlyListApiResponse.message);
    writer.writeBooleanValue("success", quoteEventHistoryIReadOnlyListApiResponse.success);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QuoteItemViewModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQuoteItemViewModel(writer: SerializationWriter, quoteItemViewModel: Partial<QuoteItemViewModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!quoteItemViewModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("currencySymbol", quoteItemViewModel.currencySymbol);
    writer.writeGuidValue("productId", quoteItemViewModel.productId);
    writer.writeStringValue("productName", quoteItemViewModel.productName);
    writer.writeNumberValue("quantity", quoteItemViewModel.quantity);
    writer.writeNumberValue("unitPrice", quoteItemViewModel.unitPrice);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QuoteManagementProblemDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQuoteManagementProblemDetails(writer: SerializationWriter, quoteManagementProblemDetails: Partial<QuoteManagementProblemDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!quoteManagementProblemDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", quoteManagementProblemDetails.detail);
    writer.writeStringValue("instance", quoteManagementProblemDetails.instance);
    writer.writeNumberValue("status", quoteManagementProblemDetails.status);
    writer.writeStringValue("title", quoteManagementProblemDetails.title);
    writer.writeStringValue("type", quoteManagementProblemDetails.type);
    writer.writeAdditionalData(quoteManagementProblemDetails.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QuoteViewModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQuoteViewModel(writer: SerializationWriter, quoteViewModel: Partial<QuoteViewModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!quoteViewModel || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", quoteViewModel.createdAt);
    writer.writeStringValue("currencyCode", quoteViewModel.currencyCode);
    writer.writeStringValue("currencySymbol", quoteViewModel.currencySymbol);
    writer.writeGuidValue("customerId", quoteViewModel.customerId);
    writer.writeCollectionOfObjectValues<QuoteItemViewModel>("items", quoteViewModel.items, serializeQuoteItemViewModel);
    writer.writeGuidValue("quoteId", quoteViewModel.quoteId);
    writer.writeStringValue("quoteStatus", quoteViewModel.quoteStatus);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QuoteViewModelApiResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQuoteViewModelApiResponse(writer: SerializationWriter, quoteViewModelApiResponse: Partial<QuoteViewModelApiResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!quoteViewModelApiResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<QuoteViewModel>("data", quoteViewModelApiResponse.data, serializeQuoteViewModel);
    writer.writeStringValue("message", quoteViewModelApiResponse.message);
    writer.writeBooleanValue("success", quoteViewModelApiResponse.success);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RegisterCustomerRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRegisterCustomerRequest(writer: SerializationWriter, registerCustomerRequest: Partial<RegisterCustomerRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!registerCustomerRequest || isSerializingDerivedType) { return; }
    writer.writeNumberValue("creditLimit", registerCustomerRequest.creditLimit);
    writer.writeStringValue("email", registerCustomerRequest.email);
    writer.writeStringValue("name", registerCustomerRequest.name);
    writer.writeStringValue("password", registerCustomerRequest.password);
    writer.writeStringValue("passwordConfirm", registerCustomerRequest.passwordConfirm);
    writer.writeStringValue("shippingAddress", registerCustomerRequest.shippingAddress);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateCustomerRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateCustomerRequest(writer: SerializationWriter, updateCustomerRequest: Partial<UpdateCustomerRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateCustomerRequest || isSerializingDerivedType) { return; }
    writer.writeNumberValue("creditLimit", updateCustomerRequest.creditLimit);
    writer.writeStringValue("name", updateCustomerRequest.name);
    writer.writeStringValue("shippingAddress", updateCustomerRequest.shippingAddress);
}
export interface UpdateCustomerRequest extends Parsable {
    /**
     * The creditLimit property
     */
    creditLimit?: number | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The shippingAddress property
     */
    shippingAddress?: string | null;
}
/* tslint:enable */
/* eslint-enable */
