/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ApiRequestBuilderNavigationMetadata, type ApiRequestBuilder } from './api/index.js';
// @ts-ignore
import { CustomerManagementRequestBuilderNavigationMetadata, type CustomerManagementRequestBuilder } from './customerManagement/index.js';
// @ts-ignore
import { InventoryManagementRequestBuilderNavigationMetadata, type InventoryManagementRequestBuilder } from './inventoryManagement/index.js';
// @ts-ignore
import { OrderProcessingRequestBuilderNavigationMetadata, type OrderProcessingRequestBuilder } from './orderProcessing/index.js';
// @ts-ignore
import { ProductCatalogRequestBuilderNavigationMetadata, type ProductCatalogRequestBuilder } from './productCatalog/index.js';
// @ts-ignore
import { QuoteManagementRequestBuilderNavigationMetadata, type QuoteManagementRequestBuilder } from './quoteManagement/index.js';
// @ts-ignore
import { apiClientProxifier, ParseNodeFactoryRegistry, SerializationWriterFactoryRegistry, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';
// @ts-ignore
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
// @ts-ignore
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
// @ts-ignore
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
// @ts-ignore
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface ApiClient extends BaseRequestBuilder<ApiClient> {
    /**
     * The api property
     */
    get api(): ApiRequestBuilder;
    /**
     * The customerManagement property
     */
    get customerManagement(): CustomerManagementRequestBuilder;
    /**
     * The inventoryManagement property
     */
    get inventoryManagement(): InventoryManagementRequestBuilder;
    /**
     * The orderProcessing property
     */
    get orderProcessing(): OrderProcessingRequestBuilder;
    /**
     * The productCatalog property
     */
    get productCatalog(): ProductCatalogRequestBuilder;
    /**
     * The quoteManagement property
     */
    get quoteManagement(): QuoteManagementRequestBuilder;
}
/**
 * Instantiates a new {@link ApiClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createApiClient(requestAdapter: RequestAdapter) {
    if (requestAdapter === undefined) {
        throw new Error("requestAdapter cannot be undefined");
    }
    const serializationWriterFactory = requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry;
    const parseNodeFactoryRegistry = requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry;
    const backingStoreFactory = requestAdapter.getBackingStoreFactory();
    
    if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
        parseNodeFactoryRegistry.registerDefaultDeserializer(JsonParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(TextParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(FormParseNodeFactory, backingStoreFactory);
    }
    
    if (serializationWriterFactory.registerDefaultSerializer) {
        serializationWriterFactory.registerDefaultSerializer(JsonSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(TextSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(FormSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(MultipartSerializationWriterFactory);
    }
    
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "http://localhost:5000";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<ApiClient>(requestAdapter, pathParameters, ApiClientNavigationMetadata, undefined);
}
/**
 * Uri template for the request builder.
 */
export const ApiClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiClientNavigationMetadata: Record<Exclude<keyof ApiClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    api: {
        navigationMetadata: ApiRequestBuilderNavigationMetadata,
    },
    customerManagement: {
        navigationMetadata: CustomerManagementRequestBuilderNavigationMetadata,
    },
    inventoryManagement: {
        navigationMetadata: InventoryManagementRequestBuilderNavigationMetadata,
    },
    orderProcessing: {
        navigationMetadata: OrderProcessingRequestBuilderNavigationMetadata,
    },
    productCatalog: {
        navigationMetadata: ProductCatalogRequestBuilderNavigationMetadata,
    },
    quoteManagement: {
        navigationMetadata: QuoteManagementRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
