/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { OrdersRequestBuilderNavigationMetadata, OrdersRequestBuilderRequestsMetadata, type OrdersRequestBuilder } from './orders/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /orderProcessing/api/v2
 */
export interface V2RequestBuilder extends BaseRequestBuilder<V2RequestBuilder> {
    /**
     * The orders property
     */
    get orders(): OrdersRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const V2RequestBuilderUriTemplate = "{+baseurl}/orderProcessing/api/v2";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const V2RequestBuilderNavigationMetadata: Record<Exclude<keyof V2RequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    orders: {
        requestsMetadata: OrdersRequestBuilderRequestsMetadata,
        navigationMetadata: OrdersRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
