global using EcommerceDDD.ApiGateway.SignalR.Hubs.Order;
global using EcommerceDDD.Core.Infrastructure.Identity;
global using EcommerceDDD.Core.Infrastructure.WebApi;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.SignalR;
global using Ocelot.Cache.CacheManager;
global using Ocelot.DependencyInjection;
global using Ocelot.Middleware;
