/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCreditLimitModelApiResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type CreditLimitModelApiResponse, type ProblemDetails } from '../../../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v2/customers/{customerId}/credit
 */
export interface CreditRequestBuilder extends BaseRequestBuilder<CreditRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreditLimitModelApiResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreditLimitModelApiResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CreditRequestBuilderUriTemplate = "{+baseurl}/api/v2/customers/{customerId}/credit";
/**
 * Metadata for all the requests in the request builder.
 */
export const CreditRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CreditRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCreditLimitModelApiResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
