// <auto-generated/>
#pragma warning disable CS0618
using EcommerceDDD.ServiceClients.ApiGateway.Api.Inventory.IncreaseStockQuantity.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EcommerceDDD.ServiceClients.ApiGateway.Api.Inventory.IncreaseStockQuantity
{
    /// <summary>
    /// Builds and executes requests for operations under \api\inventory\increase-stock-quantity
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IncreaseStockQuantityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the EcommerceDDD.ServiceClients.ApiGateway.api.inventory.increaseStockQuantity.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::EcommerceDDD.ServiceClients.ApiGateway.Api.Inventory.IncreaseStockQuantity.Item.WithProductItemRequestBuilder"/></returns>
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.Inventory.IncreaseStockQuantity.Item.WithProductItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("productId", position);
                return new global::EcommerceDDD.ServiceClients.ApiGateway.Api.Inventory.IncreaseStockQuantity.Item.WithProductItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the EcommerceDDD.ServiceClients.ApiGateway.api.inventory.increaseStockQuantity.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::EcommerceDDD.ServiceClients.ApiGateway.Api.Inventory.IncreaseStockQuantity.Item.WithProductItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::EcommerceDDD.ServiceClients.ApiGateway.Api.Inventory.IncreaseStockQuantity.Item.WithProductItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("productId", position);
                return new global::EcommerceDDD.ServiceClients.ApiGateway.Api.Inventory.IncreaseStockQuantity.Item.WithProductItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.ApiGateway.Api.Inventory.IncreaseStockQuantity.IncreaseStockQuantityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IncreaseStockQuantityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/inventory/increase-stock-quantity", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.ApiGateway.Api.Inventory.IncreaseStockQuantity.IncreaseStockQuantityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IncreaseStockQuantityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/inventory/increase-stock-quantity", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
