/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { DecreaseStockQuantityRequestBuilderRequestsMetadata, type DecreaseStockQuantityRequestBuilder } from './decreaseStockQuantity/index';
// @ts-ignore
import { HistoryRequestBuilderRequestsMetadata, type HistoryRequestBuilder } from './history/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/inventory/{productId}
 */
export interface WithProductItemRequestBuilder extends BaseRequestBuilder<WithProductItemRequestBuilder> {
    /**
     * The decreaseStockQuantity property
     */
    get decreaseStockQuantity(): DecreaseStockQuantityRequestBuilder;
    /**
     * The history property
     */
    get history(): HistoryRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithProductItemRequestBuilderUriTemplate = "{+baseurl}/api/inventory/{productId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithProductItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithProductItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    decreaseStockQuantity: {
        requestsMetadata: DecreaseStockQuantityRequestBuilderRequestsMetadata,
    },
    history: {
        requestsMetadata: HistoryRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
