// <auto-generated/>
#pragma warning disable CS0618
using EcommerceDDD.ServiceClients.IdentityServer.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace EcommerceDDD.ServiceClients.IdentityServer.Api.V2.Accounts.ResendConfirmation
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\accounts\resend-confirmation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResendConfirmationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.IdentityServer.Api.V2.Accounts.ResendConfirmation.ResendConfirmationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResendConfirmationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/accounts/resend-confirmation", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.IdentityServer.Api.V2.Accounts.ResendConfirmation.ResendConfirmationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResendConfirmationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/accounts/resend-confirmation", rawUrl)
        {
        }
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::EcommerceDDD.ServiceClients.IdentityServer.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::EcommerceDDD.ServiceClients.IdentityServer.Models.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::EcommerceDDD.ServiceClients.IdentityServer.Models.ProblemDetails">When receiving a 403 status code</exception>
        /// <exception cref="global::EcommerceDDD.ServiceClients.IdentityServer.Models.ProblemDetails">When receiving a 404 status code</exception>
        /// <exception cref="global::EcommerceDDD.ServiceClients.IdentityServer.Models.ValidationProblemDetails">When receiving a 422 status code</exception>
        /// <exception cref="global::EcommerceDDD.ServiceClients.IdentityServer.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(global::EcommerceDDD.ServiceClients.IdentityServer.Models.EmailRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(global::EcommerceDDD.ServiceClients.IdentityServer.Models.EmailRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::EcommerceDDD.ServiceClients.IdentityServer.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::EcommerceDDD.ServiceClients.IdentityServer.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "403", global::EcommerceDDD.ServiceClients.IdentityServer.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::EcommerceDDD.ServiceClients.IdentityServer.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "422", global::EcommerceDDD.ServiceClients.IdentityServer.Models.ValidationProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::EcommerceDDD.ServiceClients.IdentityServer.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::EcommerceDDD.ServiceClients.IdentityServer.Models.EmailRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::EcommerceDDD.ServiceClients.IdentityServer.Models.EmailRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::EcommerceDDD.ServiceClients.IdentityServer.Api.V2.Accounts.ResendConfirmation.ResendConfirmationRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::EcommerceDDD.ServiceClients.IdentityServer.Api.V2.Accounts.ResendConfirmation.ResendConfirmationRequestBuilder WithUrl(string rawUrl)
        {
            return new global::EcommerceDDD.ServiceClients.IdentityServer.Api.V2.Accounts.ResendConfirmation.ResendConfirmationRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ResendConfirmationRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
