/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithProductItemRequestBuilder, WithProductItemRequestBuilderRequestsMetadata } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/inventory/increase-stock-quantity
 */
export interface IncreaseStockQuantityRequestBuilder extends BaseRequestBuilder<IncreaseStockQuantityRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.inventory.increaseStockQuantity.item collection
     * @param productId Unique identifier of the item
     * @returns {WithProductItemRequestBuilder}
     */
     byProductId(productId: Guid) : WithProductItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const IncreaseStockQuantityRequestBuilderUriTemplate = "{+baseurl}/api/inventory/increase-stock-quantity";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const IncreaseStockQuantityRequestBuilderNavigationMetadata: Record<Exclude<keyof IncreaseStockQuantityRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byProductId: {
        requestsMetadata: WithProductItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["productId"],
    },
};
/* tslint:enable */
/* eslint-enable */
