/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { QuotesRequestBuilderNavigationMetadata, QuotesRequestBuilderRequestsMetadata, type QuotesRequestBuilder } from './quotes/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /quoteManagement/api/v2
 */
export interface V2RequestBuilder extends BaseRequestBuilder<V2RequestBuilder> {
    /**
     * The quotes property
     */
    get quotes(): QuotesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const V2RequestBuilderUriTemplate = "{+baseurl}/quoteManagement/api/v2";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const V2RequestBuilderNavigationMetadata: Record<Exclude<keyof V2RequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    quotes: {
        requestsMetadata: QuotesRequestBuilderRequestsMetadata,
        navigationMetadata: QuotesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
