// <auto-generated/>
#pragma warning disable CS0618
using EcommerceDDD.ServiceClients.InventoryManagement.Api.V2.Internal.Inventory.Item.DecreaseStockQuantity;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EcommerceDDD.ServiceClients.InventoryManagement.Api.V2.Internal.Inventory.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\internal\inventory\{productId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProductItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The decreaseStockQuantity property</summary>
        public global::EcommerceDDD.ServiceClients.InventoryManagement.Api.V2.Internal.Inventory.Item.DecreaseStockQuantity.DecreaseStockQuantityRequestBuilder DecreaseStockQuantity
        {
            get => new global::EcommerceDDD.ServiceClients.InventoryManagement.Api.V2.Internal.Inventory.Item.DecreaseStockQuantity.DecreaseStockQuantityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.InventoryManagement.Api.V2.Internal.Inventory.Item.WithProductItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProductItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/internal/inventory/{productId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EcommerceDDD.ServiceClients.InventoryManagement.Api.V2.Internal.Inventory.Item.WithProductItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProductItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/internal/inventory/{productId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
