/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type UpdateorderstatusRequestBuilder, UpdateorderstatusRequestBuilderRequestsMetadata } from './updateorderstatus/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v2/signalr
 */
export interface SignalrRequestBuilder extends BaseRequestBuilder<SignalrRequestBuilder> {
    /**
     * The updateorderstatus property
     */
    get updateorderstatus(): UpdateorderstatusRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SignalrRequestBuilderUriTemplate = "{+baseurl}/api/v2/signalr";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SignalrRequestBuilderNavigationMetadata: Record<Exclude<keyof SignalrRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    updateorderstatus: {
        requestsMetadata: UpdateorderstatusRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
